- src/components/MsgPublish.vue
- src/views/connections/ConnectionsContent.vue
> feat(msg_publish): remove required verification of the payload

- src/lang/connections.ts
- src/utils/mqttUtils.ts
- src/views/connections/ConnectionForm.vue
- src/views/connections/types.ts
> fix(connections): fix certificate certification issues

- src/assets/scss/element/element-reset.scss
- src/assets/scss/theme/dark.scss
- src/assets/scss/theme/light.scss
- src/assets/scss/theme/night.scss
- src/views/connections/ConnectionForm.vue
> feat(connectionForm.vue): add json lang to will payload & fix label width

- src/assets/scss/element/element-reset.scss
- src/utils/getFiles.ts
> fix(getFiles): error prompt when SSL verification fails to read the file

- src/store/modules/app.ts
- src/views/connections/ConnectionsDetail.vue
> fix(connections): fixed messages duplicated

- src/components/MsgLeftItem.vue
- src/components/SubscriptionsList.vue
> fix(msg): fix the issue of the incorrect color marking

- package.json
- src/components/Contextmenu.vue
- src/types/locale.d.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/connections/ConnectionsList.vue
- src/views/connections/index.vue
- src/views/connections/types.ts
- yarn.lock
> feat(conection): add delete connection contextmenu

- src/views/connections/ConnectionsDetail.vue
> feat(msg): add convert method when received message

- src/assets/scss/element/element-reset.scss
- src/lang/connections.ts
- src/views/connections/ConnectionsDetail.vue
> feat(msg): add decoded option to received message

- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionInfo.vue
Adjust icon style. Remove `:hover` fake class style.
> fix(connections): adjust icon style for 'ConnectionInfo.vue'

- package.json
- src/utils/logger.ts
- src/views/log/index.vue
- vue.config.js
- yarn.lock
> feat(logs): Optimize log loading

- src/background.ts
- src/components/SubscriptionsList.vue
- src/utils/logger.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/log/index.vue
- vue.config.js
I set logger for the fellow situation
* Message publish success
* Message receive
* Script/Import/Export data status 
* MQTT.js status record
Parts not recorded as logs
* UI operation
* Some operation  just affect the view module data (such as filter out some data by condition)
> fix(logs): set logger for connectionDetail page

- src/background.ts
- src/components/MsgPublish.vue
- src/views/connections/index.vue
fix:#[427](https://github.com/emqx/MQTTX/issues/427)
> fix(MsgPublish): fix cannot initialized editor jump from creation page

- src/lang/connections.ts
- src/utils/mqttUtils.ts
- src/views/connections/ConnectionForm.vue
> fix(ssl): set rejectUnauthorized to true by default

- src/views/connections/ConnectionForm.vue
> fix(ConnectionForm): fix page init issue when create after editing

- src/components/Editor.vue
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionsDetail.vue
- src/views/log/index.vue
* add auto-scroll function for log page
* adjust the `line-space` and `wordWrap` for log editor
* log message enhance
The editor `line-space` is higher now.
Support auto-scroll function.
Support word Wrap.
> feat(log): add auto scroll buttom for log page & enhance log message

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/help_wanted.md
> docs(issue): add issue template for help wanted and feature request

- src/components/Editor.vue
- src/components/MsgPublish.vue
fix(MsgPublish): fix multiple editors that were not destroyed, causing failure to bind payload
> fix(MsgPublish): fix multiple editors that were not destroyed

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- README-CN.md
- README-JP.md
- README.md
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: <https://github.com/emqx/MQTTX/blob/master/CONTRIBUTING.md>
Users cannot fully understand how to participate in the construction project.
Add contributing documentation
> docs(github): add contributing file

- vue.config.js
Windows package name is `MQTTX Setup ${version}.${ext}`
None
Now, the name change to `MQTTX.Setup.${version}.${ext}`
> build(win): modify windows package name

- .github/workflows/build_packages.yaml
- .github/workflows/upload_github_release_asset.sh
- docs/manual-cn.md
- docs/manual-jp.md
- docs/manual.md
- package.json
- src/background.ts
- src/components/MsgPublish.vue
- src/main.ts
- src/utils/logger.ts
- vue.config.js
- yarn.lock
Signed-off-by: oceanlvr <657531018@qq.com>### PR Checklist
Need to manually release version
GitHub Action automatically build and release version
>  chore(CI): add github actions

- README-CN.md
- README.md
- package.json
Signed-off-by: oceanlvr <657531018@qq.com>### PR Checklist
Add blank on readme file.
> fix(logs): fix windows filename error & build error

- src/views/connections/ConnectionsDetail.vue
Unable to record the error log.
None
Can record the complete log correctly
Ref:
https://stackoverflow.com/questions/4816099/chrome-sendrequest-error-typeerror-converting-circular-structure-to-json
> fix(connections): fix can not add error connect fail log

- src/components/Editor.vue
- src/views/log/index.vue
Keep the oldest message when opening the page for the first time.
#510 
Scroll to the footer when opening the page for the first time
Add new message:
Log page init:
> feat(log): scroll to buttom shen opening log page

- README-CN.md
- README-JP.md
- README.md
Add action status badge on readme file.
None
> docs(readme): add action status badge

- src/assets/scss/theme/dark.scss
- src/assets/scss/theme/light.scss
- src/assets/scss/theme/night.scss
- src/components/SubscriptionsList.vue
Topic box clicks with a weak response.
#511 
> UI(topicList): enhance topic filter click UI\UX

- src/assets/scss/base.scss
- src/assets/scss/theme/dark.scss
- src/assets/scss/theme/light.scss
- src/components/SubscriptionsList.vue
> style(theme): modify some colors

- src/api/connection.ts
- src/database/index.ts
- src/lang/connections.ts
- src/store/modules/app.ts
- src/types/global.d.ts
- src/utils/getCollectionId.ts
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionsList.vue
- src/views/connections/index.vue
- src/views/connections/types.ts
- src/views/window/Window.vue
#375 
add rename and new collection menu.
https://user-images.githubusercontent.com/36698124/112271363-cd85cf80-8cb5-11eb-8d0f-46c5d7086a4e.mp4
> feat(connection): support connection collection delete & rename & add(drop)

- src/background.ts
- src/views/connections/ConnectionsList.vue
None
#375 
https://user-images.githubusercontent.com/36698124/113247613-f75e7800-92ed-11eb-9211-dc7b262cdd48.mp4
> feat(connection): support drag connnection to create new windows

- src/views/connections/ConnectionsList.vue
When we drag and drop connection `n` times, we will get `n` new windows.
#375 
Just create only one new window when we drop out the window.
> fix(connnection): fix connection drag create multi windows

- docs/manual-jp.md
- docs/manual.md
> docs(medium): modify medium account link

- src/api/connection.ts
- src/components/MsgPublish.vue
- src/database/index.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/connections/types.ts
Support quick lookup of the message payload history.
#428 
> feat(connection): add local storage for messageHeader

- README-CN.md
- README-JP.md
- README.md
- docs/manual-cn.md
- docs/manual-jp.md
- docs/manual.md
- src/views/about/index.vue
https://twitter.com/emqtt -> https://twitter.com/EMQTech
> docs: modify twitter link

- README-CN.md
- README-JP.md
- README.md
> docs(connectionsList): update emq twitter icon

- README-CN.md
- README-JP.md
- README.md
> docs(readme): update twitter icon

- src/components/MsgPublish.vue
- src/utils/mqttUtils.ts
None
support remove duplicates for payload & headers.
> fix(MsgPublish): support remove duplicates for payload & headers

- src/api/connection.ts
- src/components/MsgPublish.vue
- src/utils/connections.ts
- src/views/connections/ConnectionsList.vue
- src/views/connections/types.ts
Support keep the connection sequence.
None.
keep connection and collection sequence correctly.
> fix(connectionList): fix connection & collection tree sequence issue

- package.json
- src/api/connection.ts
- src/components/ClearUpHistoryData.vue
- src/components/MsgPublish.vue
- src/database/index.ts
- src/lang/connections.ts
- src/lang/settings.ts
- src/views/settings/index.vue
> feat(settings): support remove history suggestion data

- src/views/connections/ConnectionsList.vue
check and hover color unexpected.
None.
replace by normal color.
> fix(connectionsList): fix connection lists theme color issue

- src/components/MsgPublish.vue
- src/views/connections/ConnectionsDetail.vue
> fix(MsgPublish): fix publish history message index issue

- src/main/updateChecker.ts
- src/views/about/index.vue
> chore(package): v1.5.3 -> v1.5.4

- .github/CONTRIBUTING.md
> Typo readme for contributing

- .github/PULL_REQUEST_TEMPLATE.md
- src/components/ExportData.vue
- src/components/MsgPublish.vue
- src/components/SubscriptionsList.vue
- src/database/index.ts
- src/lang/common.ts
- src/lang/connections.ts
- src/lang/settings.ts
- src/store/getter.ts
- src/store/modules/app.ts
- src/types/global.d.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/settings/index.vue
Add auto resubscribe status settings and methods
Example: None
> feat(subscriptions): add resubscribe method

- package.json
- vue.config.js
- yarn.lock
> chore(deps): bump vue-cli-plugin-electron-builder from 1.4.6 to 2.0.0

- README-CN.md
The contact info block has invalid picture
None
The contact info block has been deleted in README-CN.md and add community block in READM-CN.md
> doc(README-CN): add community block & delete contact info block

- src/components/MsgPublish.vue
Example: None
Fix this error info on the console.
> fix(msg): fix cannot read property payloadType of undefined

- README-CN.md
- README-JP.md
- README.md
- src/background.ts
The window can be resized infinitely.
Example: None
Set the minimum height and width that can be resized
> feat(main): add min width and height on browser window

- src/assets/scss/element/element-reset.scss
- src/components/MsgPublish.vue
- src/utils/element.ts
Import useless el-cascader component
Example: None
Remove it
> fix(msg): remove unused component & modify some styles

- .eslintrc.js
- src/views/connections/ConnectionsDetail.vue
Cannot send data after converting to base64 and hex
None
The value stored in the historical record should be the original value
> fix(connections): fix can't send hex & base64 payload on histroy

- package.json
- yarn.lock
* https://github.com/mqttjs/MQTT.js/issues/1152
* https://github.com/mqttjs/MQTT.js/pull/1162
* https://github.com/emqx/MQTTX/issues/595
close https://github.com/emqx/MQTTX/issues/595
> fix(deps): Upgrade MQTT.js to v4.2.6 to fix reconnect bug

- README-CN.md
- README.md
- yarn.lock
> chore(package): bump some dependencies

- src/components/MsgPublish.vue
- src/components/SubscriptionsList.vue
- src/lang/about.ts
- src/lang/common.ts
- src/lang/connections.ts
- src/lang/settings.ts
Hide the subscription list, the editor is obscured after it is displayed again
Example: #593 
The editor can be resized correctly
> fix(msg): fix can not resize the editor

- package.json
- vue.config.js
Example: None
Add deb and rpm installation packages under Linux
> feat(config): add rpm & deb package

- package.json
- src/background.ts
- src/components/ImportData.vue
- src/main/newWindow.ts
- src/main/saveExcel.ts
- src/main/saveFile.ts
- src/main/updateChecker.ts
- src/views/about/index.vue
- src/views/connections/ConnectionForm.vue
- yarn.lock
The current version of Electron is 5.0.0
Example: None
Bump Electron version to 11.4.8
> chore(package): bump electron to v11.4.8

- vue.config.js
This warning appears cyclically on dev mode.
Example: None
Disable host check.
> fix(config): fix console warning aboout websocket connect

- src/assets/scss/base.scss
- src/assets/scss/mixins.scss
- src/assets/scss/variable.scss
- src/components/Editor.vue
- src/components/MsgPublish.vue
- src/lang/common.ts
- src/views/connections/ConnectionInfo.vue
- src/views/connections/ConnectionsDetail.vue
- src/views/log/index.vue
- src/views/script/index.vue
- vue.config.js
> refactor(editor): reset editor config to adapt the new interface

- src/views/about/index.vue
> refactor(about): update copyright

- README-CN.md
- README-JP.md
- README.md
> docs(readme): update readme

- .github/CONTRIBUTING.md
- .github/CONTRIBUTING_CN.md
- src/views/connections/ConnectionsDetail.vue
Example: none
Fix this error info on console
> fix(connection): remove window onresize event

- src/assets/scss/element/element-reset.scss
- src/assets/scss/theme/custom/log-editor-night.json
- src/assets/scss/theme/dark.scss
- src/assets/scss/theme/light.scss
- src/assets/scss/theme/night.scss
- src/components/Editor.vue
- src/components/Leftbar.vue
- src/views/Home.vue
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionsList.vue
- src/views/log/index.vue
> style(theme): adapt the night and dark theme interface

- src/lang/settings.ts
- src/views/settings/index.vue
> fix(i18n): add missing theme options i18n

- package.json
- yarn.lock
Get these warnings.
Example: none
Remove syntax warnings.
> chore(package): fixed the sass version

- gen-version.js
- package.json
- scripts/gen-version.js
- src/version.ts
- vue.config.js
none
Example: none
Add scripts folder, and remove source map on production.
> pref(config): remove source map on production

- src/types/global.d.ts
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionInfo.vue
- src/views/connections/ConnectionsDetail.vue
> refactor(types): imporve types defined

- src/assets/scss/element/element-reset.scss
- src/views/script/index.vue
> style(element): change button border width to 1px

- src/background.ts
- src/database/database.config.ts
- src/database/migration/1627614417814-initTable.ts
- src/database/models/ConnectionEntity.ts
- src/database/models/MessageEntity.ts
- src/database/models/SubscriptionEntity.ts
- src/database/models/WillEntity.ts
- src/database/services/ConnectionService.ts
- src/database/useConnection.ts
- src/main.ts
- src/types/global.d.ts
- src/utils/mqttUtils.ts
- src/views/connections/ConnectionForm.vue
init table models use by `migration` script
None.
init tables
> migration(db): init table models

- package.json
- src/background.ts
- src/database/database.config.ts
- src/database/migration/1627697951611-initTable.ts
- src/database/models/SettingEntity.ts
- src/database/services/SettingService.ts
- src/database/useServices.ts
> refactor(settings): refactor settings model

- src/database/models/CollectionEntity.ts
- src/database/models/ConnectionEntity.ts
- src/database/models/MessageEntity.ts
- src/database/models/WillEntity.ts
- src/database/services/ConnectionService.ts
refactor connection service API
> refactor(connection): migration connection api to service

- src/api/connection.ts
- src/database/index.ts
- src/database/models/HistoryMessageHeaderEntity.ts
- src/database/models/HistoryMessagePayloadEntity.ts
- src/database/services/ConnectionService.ts
- src/database/services/HistoryMessageHeaderService.ts
- src/database/services/HistoryMessagePayloaderService.ts
- src/database/services/MessageService.ts
- src/database/services/ScriptService.ts
- src/store/modules/app.ts
- src/types/global.d.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/connections/ConnectionsList.vue
- src/views/connections/index.vue
refactor misc services layer API, next step we need to do more test and refactor current collection & will & subscription model.
None.
None.
> refactor(services): misc services API refactor

- src/database/models/CollectionEntity.ts
- src/database/models/ConnectionEntity.ts
- src/database/models/MessageEntity.ts
- src/database/models/SubscriptionEntity.ts
- src/database/models/WillEntity.ts
- src/database/services/CollectionService.ts
- src/database/services/ConnectionService.ts
- src/database/services/HistoryMessageHeaderService.ts
- src/database/services/HistoryMessagePayloaderService.ts
- src/database/services/MessageService.ts
- src/database/services/ScriptService.ts
`ManyToOne` relation can't be nullable.
None
Finish the service refactor, we should do more test in UI layer.
> refactor(services): refactor collection service & ManyToOne relation

- .github/CONTRIBUTING.md
- .github/CONTRIBUTING_CN.md
- package.json
- src/api/connection.ts
- src/database/database.config.ts
- src/database/models/CollectionEntity.ts
- src/database/models/ConnectionEntity.ts
- src/database/models/HistoryMessageHeaderEntity.ts
- src/database/models/HistoryMessagePayloadEntity.ts
- src/database/models/MessageEntity.ts
- src/database/models/SubscriptionEntity.ts
- src/database/models/WillEntity.ts
- src/database/services/CollectionService.ts
- src/database/services/ConnectionService.ts
- src/database/useServices.ts
- src/types/global.d.ts
- src/views/connections/ConnectionsList.vue
- src/views/connections/index.vue
replace current collection service API
None
> refactor(services): replace current collection service API

- src/api/connection.ts
- src/database/models/WillEntity.ts
- src/database/services/CollectionService.ts
- src/database/services/ConnectionService.ts
- src/utils/connections.ts
- src/views/connections/ConnectionsList.vue
- src/views/connections/index.vue
> refactor(service): refactor collection sort and sequence API

- src/components/ClearUpHistoryData.vue
- src/components/ExportData.vue
- src/database/database.config.ts
- src/database/models/HistoryMessageHeaderEntity.ts
- src/database/models/HistoryMessagePayloadEntity.ts
- src/database/models/SettingEntity.ts
- src/database/services/CollectionService.ts
- src/database/services/ConnectionService.ts
- src/types/global.d.ts
- src/utils/connections.ts
- src/utils/time.ts
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionsDetail.vue
- src/views/connections/index.vue
- src/views/window/Window.vue
> refactor(service): refactor suggest connection service API

- src/database/services/CollectionService.ts
- src/database/services/ConnectionService.ts
- src/types/global.d.ts
- src/views/connections/ConnectionsList.vue
can't remove collection currently.
None.
refactor & fix collection service API.
> fix(collection): fix collection service API

- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionsList.vue
- src/views/connections/index.vue
> fix(connection):fix connection state sync issue

- src/lang/common.ts
> fix(common): modify emqx cloud link

- src/background.ts
- src/database/database.config.ts
- src/database/migration/1630403733964-messages.ts
- src/database/models/MessageEntity.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/connections/ConnectionsList.vue
- src/views/connections/index.vue
> fix(index): fix empty page issue

- src/database/database.config.ts
- src/database/migration/1630497638704-collection.ts
- src/database/models/CollectionEntity.ts
- src/database/services/CollectionService.ts
- src/database/services/ConnectionService.ts
- src/utils/connections.ts
- src/views/connections/ConnectionsList.vue
> fix(connection): collections tree composition issue

- src/views/connections/ConnectionsList.vue
> fix(collection): enhance collection allow drop condition

- src/database/database.config.ts
- src/database/migration/1630572256038-historyConnections.ts
- src/database/models/HistoryConnectionEntity.ts
- src/database/models/SettingEntity.ts
- src/database/services/ConnectionService.ts
> fix(connection): refactor suggestion connections

- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionsDetail.vue
- src/views/script/index.vue
> fix(connectionDetail): fix connection detail scroll issue

- src/background.ts
- src/views/connections/ConnectionsDetail.vue
> fix(message): removed message ipc services

- src/utils/SystemTopicUtils.ts
- src/utils/convertPayload.ts
- src/utils/getClientId.ts
- src/utils/getCollectionId.ts
- src/utils/matchMultipleSearch.ts
- src/utils/time.ts
- src/utils/topicMatch.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/connections/ConnectionsList.vue
> fix(collection): remove/add collection trigger reload events

- src/components/SubscriptionsList.vue
- src/database/services/CollectionService.ts
- src/database/services/ConnectionService.ts
- src/views/connections/ConnectionsDetail.vue
> fix(subscription): fix subscription remove failed issue

- package.json
- src/components/MessageList.vue
- src/main.ts
- src/types/shims-vue.d.ts
- yarn.lock
a lot of raw `push` operations in the short time lead to lag UI performance, use `vue-virtual-scroller` improve list render performance.
None.
better performance in the message list component.
> feat(messages): ⚡ improve message list performence

- README-CN.md
- README-JP.md
- README.md
> docs(readme): fix slack badge

- README-CN.md
- README-JP.md
- README.md
update document.
Example: \#123
> doc(readme): update tech stack

- src/components/ExportData.vue
- src/components/UseScript.vue
- src/database/services/MessageService.ts
- src/utils/time.ts
- src/views/connections/ConnectionsList.vue
- src/views/script/index.vue
> fix(message): fix service empty array query issue

- src/assets/scss/mixins.scss
- src/components/MsgLeftItem.vue
> feat(msg): add retain flag

- src/store/modules/app.ts
After refreshing the page, the status in the settings is disabled
Example: none
Refresh the page, the status in the settings is retained.
> fix(store): fix cant sync the data to shared data

- src/assets/scss/element/element-reset.scss
- src/assets/scss/theme/dark.scss
- src/assets/scss/theme/light.scss
- src/assets/scss/theme/night.scss
> style(element): adaptation of the skeleton screen theme

- src/components/MsgLeftItem.vue
- src/components/MsgRightItem.vue
- src/database/services/ConnectionService.ts
- src/views/connections/ConnectionsDetail.vue
Flash animation because of `vue-virtual-scroller`
None.
Remove enter and leave animation temporally. Keep the list of highest performance first.(and better compatibility)
Are there any specific instructions or things that should be known before review?
> fix(message): fix message enter & leave flash issue

- src/database/models/HistoryConnectionEntity.ts
- src/database/services/ConnectionService.ts
> fix(connection): remove useless codes

- src/database/services/ConnectionService.ts
> fix(will): will model cascade remove issue

- src/components/MsgPublish.vue
> fix(msgPublish): payload changed after send msg

- src/views/connections/ConnectionsList.vue
- src/views/connections/index.vue
Example: no
delete group reload
fix delete group will not reload
Other information
> fix(connection): delete collection reload bug

- src/views/connections/ConnectionsList.vue
> fix(collection): add delete confirm

- src/utils/convertPayload.ts
> fix(MsgPublish): fix base64 convert issue

- src/main/newWindow.ts
New window unsuccess load.
None.
Fixes an issue where MQTT X could not be loaded because of an upgrade `elelctron`
> fix(newWindows): fix new windows loading issue

- src/database/services/CollectionService.ts
- src/database/services/ConnectionService.ts
- src/views/connections/ConnectionsList.vue
> fix(connectionList): fix collectionId null issue

- src/components/MsgPublish.vue
- src/lang/common.ts
- src/types/global.d.ts
- src/views/connections/ConnectionsDetail.vue
https://github.com/mqttjs/MQTT.js/pull/827/commits
https://github.com/mqttjs/MQTT.js/pull/1359
https://github.com/mqttjs/MQTT.js/issues/1334
add message mqtt5 props support
> feat(mqtt5): add message mqtt5 props support

- src/components/MsgPublish.vue
> refactor(mqtt5): adjust meta card UI

- src/components/MsgPublish.vue
> style(meta): modify some meta card styles

- src/components/SubscriptionsList.vue
- src/database/services/ConnectionService.ts
- src/lang/connections.ts
Only can sub one topic once.
Example: \#123
> feat(subscriptions): support subscribe muti-topics

- src/components/MsgLeftItem.vue
- src/components/MsgRightItem.vue
- src/database/database.config.ts
- src/database/migration/1637636965786-messageProps.ts
- src/database/models/MessageEntity.ts
- src/database/services/ConnectionService.ts
- src/database/services/MessageService.ts
- src/views/connections/ConnectionsDetail.vue
> feat(messagelist): support messagelist props ui

- src/components/SubscriptionsList.vue
- src/database/services/ConnectionService.ts
can't insert service layer due to dulp id.
Example: \#123
> fix(subscribe): multi subscribes insert issue

- src/components/MsgLeftItem.vue
- src/components/MsgPublish.vue
- src/components/MsgRightItem.vue
- src/database/database.config.ts
- src/database/migration/1638081576988-enhanceMessageType.ts
- src/database/models/ConnectionEntity.ts
- src/database/models/WillEntity.ts
- src/database/services/ConnectionService.ts
- src/database/services/MessageService.ts
- src/types/global.d.ts
- src/views/connections/ConnectionsDetail.vue
enhance message props type, remove `blob` type (service layer) which is unstable.
```js
// buffer to string
bufferObj.toString('utf-8')
// string to buffer
Buffer.from(bufferObj)
```
> refactor(message): enhance message props type

- src/components/MsgLeftItem.vue
- src/components/MsgPublish.vue
- src/components/MsgRightItem.vue
> fix(msg): fix properties is undefined

- src/components/MsgLeftItem.vue
- src/components/MsgRightItem.vue
- src/views/connections/ConnectionsDetail.vue
MQTT v3 will still display user properties.
Example: \#123
Only show the user properties when MQTT version is v5
> fix(msg): fix display user props issue

- src/components/MsgPublish.vue
- src/lang/connections.ts
> feat(msg): add tooltip when meta button disabled

- src/assets/scss/mixins.scss
- src/assets/scss/theme/dark.scss
- src/assets/scss/theme/light.scss
- src/assets/scss/theme/night.scss
- src/components/MsgLeftItem.vue
- src/components/MsgPublish.vue
- src/components/MsgRightItem.vue
Example: \#123
@oceanlvr It's a temporary setup, but a little better than before. In the prototype diagram, the effect after implementation is actually not too good
> style(msg): modify user properties display styles

- src/background.ts
- src/components/Editor.vue
- src/main/systemTheme.ts
- src/views/Home.vue
sync then os theme setting
Example: \#123
> feat(settings): sync with os theme setting

- src/components/MsgPublish.vue
- src/database/models/ConnectionEntity.ts
- src/database/services/MessageService.ts
- src/views/connections/ConnectionsDetail.vue
> fix(message): fix message prop incorrect insert

- src/components/MsgPublish.vue
- src/database/models/ConnectionEntity.ts
- src/database/services/ConnectionService.ts
- src/database/services/MessageService.ts
- src/types/global.d.ts
- src/utils/handleString.ts
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionsDetail.vue
> fix(connection): fix properties has default value issue

- src/components/MsgPublish.vue
- src/lang/common.ts
- src/types/global.d.ts
> fix(msg): add confirm reset prompt and fix can not load user properties

- src/database/services/MessageService.ts
- src/types/global.d.ts
- src/views/connections/ConnectionsDetail.vue
> fix(msg): fix correlation data is buffer type

- src/components/KeyValueEditor.vue
- src/components/MsgPublish.vue
- src/views/connections/ConnectionForm.vue
> feat(components): add key value editor component

- src/components/KeyValueEditor.vue
- src/components/MsgPublish.vue
- src/database/services/ConnectionService.ts
- src/types/global.d.ts
> fix(msg): properties state lsolation

- src/views/connections/ConnectionForm.vue
> feat(connection): add unit for connection form

- src/views/connections/ConnectionsDetail.vue
Example: #815 
Remove useless properties.
> fix(connection): fix pass the __ob__ field to user properties

- src/database/database.config.ts
- src/database/migration/1639031638009-clientid.ts
- src/database/models/ConnectionEntity.ts
Can not create two connections with a different host and same client id
Example: #799 
> fix(connection): fix client id is unique in database

- src/views/connections/ConnectionForm.vue
> fix(connection): add unit to session expiry interval

- src/components/SubscriptionsList.vue
- src/database/database.config.ts
- src/database/migration/1639375963172-subscriptionIdentifier.ts
- src/database/models/SubscriptionEntity.ts
> feat(subscriptions): add sub identifier field

- src/components/MsgPublish.vue
- src/components/SubscriptionsList.vue
- src/lang/connections.ts
- src/types/global.d.ts
- src/views/settings/index.vue
> feat(subscriptions): add sub identifier

- src/components/MsgPublish.vue
> fix(msg): remove reset meta data function

- src/views/connections/ConnectionsDetail.vue
> fix(connection): fix can sent empty topic when set the topic alias

- package.json
- src/components/ClearUpHistoryData.vue
- src/components/ExportData.vue
- src/components/ImportData.vue
- src/components/SubscriptionsList.vue
- src/components/TimedMessage.vue
- src/components/UseScript.vue
- src/version.ts
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionsDetail.vue
- src/views/connections/ConnectionsList.vue
- src/views/script/index.vue
> refactor(i18n): replace some /$t to /$tc

- src/assets/scss/mixins.scss
- src/components/KeyValueEditor.vue
- src/components/MsgLeftItem.vue
- src/components/MsgRightItem.vue
> style(msg): use key value editor to display user properties

- src/components/SubscriptionsList.vue
- src/views/connections/ConnectionsDetail.vue
> feat(log): add properties log

- src/components/SubscriptionsList.vue
> fix(subs): fix resub can not sync the all data

- src/background.ts
- src/database/database.config.ts
- src/database/migration/1639730106721-syncOsTheme.ts
- src/database/models/SettingEntity.ts
- src/lang/settings.ts
- src/store/getter.ts
- src/store/modules/app.ts
- src/types/global.d.ts
- src/views/Home.vue
- src/views/settings/index.vue
> feat(settings): add sync the os theme field

- src/components/ClearUpHistoryData.vue
- src/components/Contextmenu.vue
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionsDetail.vue
- src/views/connections/ConnectionsList.vue
> feat(connection): add edit button on contextmenu & add some logs

- src/lang/about.ts
- src/lang/common.ts
- src/views/about/index.vue
> feat(about): update about page

- src/database/services/ConnectionService.ts
collection importing issue
#839 
> fix(import): collection importing issue

- docs/manual.md
> docs(manual): fix docs image path

- package.json
- src/components/SubscriptionsList.vue
- src/router/index.ts
- src/views/connections/ConnectionsDetail.vue
- yarn.lock
> chore(package): bump mqtt to 4.3.0 to fix types error

- package.json
- src/components/SubscriptionsList.vue
- src/lang/connections.ts
- yarn.lock
> feat(subscriptions): support edit topic

- src/views/connections/ConnectionsList.vue
> fix(connection): isolating connections in the new window

- src/views/connections/ConnectionsDetail.vue
Logs can not record which connection.
Example: \#123
> refactor(log): improve the log info

- README-CN.md
- README-JP.md
- README.md
- src/main/newWindow.ts
- src/views/connections/index.vue
- src/views/window/Window.vue
> fix(window): fix can not resub topic on new window

- src/components/Contextmenu.vue
- src/components/SubscriptionsList.vue
- src/database/database.config.ts
- src/database/migration/1640846307653-topicDisabled.ts
- src/database/models/SubscriptionEntity.ts
- src/lang/common.ts
- src/types/global.d.ts
- src/views/connections/ConnectionsDetail.vue
> feat(subscriptions): support disable and enable topic

- src/views/connections/ConnectionsDetail.vue
> feat(log): add some logs

- package.json
- src/version.ts
> chore(pkg): 1.7.1 -> 1.7.2

- src/lang/connections.ts
- src/views/connections/ConnectionForm.vue
Reconnect period is a default value
Example: none
Expose the reconnect period to users
> feat(connection): support set reconnect period when create

- src/components/SubscriptionsList.vue
[874](https://github.com/emqx/MQTTX/issues/874)
> fix(subscription): fix sublist refrence copy issue

- src/assets/scss/mixins.scss
> style(msg): modify msg item max width

- src/views/about/index.vue
- vue.config.js
> Support build more arm64 pkg

- README-CN.md
- README-JP.md
- README.md
- docs/manual-cn.md
- docs/manual-jp.md
- docs/manual.md
- package.json
- src/lang/about.ts
- src/lang/common.ts
- src/main/getMenuTemplate.ts
- src/views/about/index.vue
> refactor(src): emq x -> emqx

- vue.config.js
> chore(config): add win32 & arm build

- src/utils/mqttUtils.ts
- src/views/connections/ConnectionForm.vue
> feat(connection): backward support for mqtt 3.1

- src/components/MsgPublish.vue
- src/components/SubscriptionsList.vue
- src/lang/connections.ts
- src/utils/convertPayload.ts
> feat(subscriptions): add comments to QoS

- src/views/connections/ConnectionForm.vue
Example: \#123
It's better than radio button.
> refactor(connection): replace ssl radio button to switch button

- package.json
- src/version.ts
> chore(pkg): 1.7.2 -> 1.7.3

- src/components/Leftbar.vue
Sidebar activation status error.
Example: \#123
Fix sidebar activation status error, now the sidebar create button is correctly activated when creating a new connection.
> fix(sidebar): fix sidebar activation status error

- src/views/about/index.vue
> chore(about): modify utm_capaign for emqx broker link

- package.json
- src/lang/connections.ts
- yarn.lock
> chore(package): bump mqtt to 4.3.7

- src/components/Ipc.vue
- src/main/getMenuTemplate.ts
- src/views/connections/ConnectionsDetail.vue
> feat(menu): add new window menu

- src/lang/common.ts
- src/lang/connections.ts
- src/views/connections/ConnectionsList.vue
> feat(connection): support duplicate the connection

- src/lang/common.ts
> chore(cloud-link): modify utm source for cloud link

- src/lang/common.ts
> chore(cloud-link): modify utm medium for cloud link

- src/components/ClearUpHistoryData.vue
- src/lang/common.ts
- src/lang/connections.ts
- src/lang/script.ts
> fix(lang): fix some case issue

- src/components/MessageList.vue
- src/views/connections/ConnectionsDetail.vue
Can not clear long message
Example: #922
fix it
> fix(message): fix can not clear long message

- src/views/connections/ConnectionsDetail.vue
> fix(message): fix show duplicate long message in diff connection

- cli/README.md
> docs(readme): update cli readme

- cli/.gitignore
- cli/.npmignore
- cli/bin/index.js
- cli/package.json
- cli/src/index.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
- cli/tsconfig.json
Example: \#123
add main module & modify bin executable file.
> feat(cli): add main module & modify bin executable file

- cli/README-CN.md
- cli/README.md
- web/README-CN.md
> docs(readme): update homebrew

- web/src/router/index.ts
- web/vue.config.js
> chore(web): modify router mode & public path

- web/public/index.html
Example: \#123
Set the page title and description using env variables.
Create a file named `.env.local` in project root, like:
```
VUE_APP_PAGE_TITLE=Easy-to-Use Online MQTT Client | Try Now
VUE_APP_PAGE_DESCRIPTION=Online MQTT 5.0 client on the web, using MQTT over WebSocket to connect to the MQTT Broker and test message publishing and receiving in the browser.
```
> feat(page): set page title & description

- .github/workflows/deploy_web.yaml
Example: \#123
Add an action to publish MQTTX web
> feat(ci): add deploy website

- package.json
- src/background.ts
- src/main/updateChecker.ts
- vue.config.js
- yarn.lock
Test the automatic update feature
> feat(src/main/updateChecker.ts): add a feature for automatic updates

- web/README-CN.md
- web/README.md
- web/src/lang/common.ts
- web/src/views/about/index.vue
> chore(web): modify utm params & update web readme

- .github/workflows/deploy_web.yaml
Example: \#123
Add an action to publish MQTTX web
> fix(deploy): upload  dist to oss

- web/package.json
- web/src/main.ts
- web/yarn.lock
Example: \#123
add google analytics
> feat(web): add google analytics

- src/utils/mqttUtils.ts
Example: \#123
Modify the default mqtt version from 3.1.1 to 5.0.
> chore(desktop): modify the default mqtt version from 3.1.1 to 5.0

- .gitignore
- web/src/views/connections/ConnectionForm.vue
- web/src/views/connections/index.vue
Example: \#123
Modify the default mqtt version from 3.1.1 to 5.0.
> chore(web): modify the default mqtt version from 3.1.1 to 5.0

- LICENSE
Example: \#123
Recover the root license file.
> fix(license): recover the root license file

- src/views/about/index.vue
- web/src/components/Leftbar.vue
- web/src/lang/about.ts
- web/src/lang/common.ts
- web/src/views/about/index.vue
- web/src/views/connections/ConnectionForm.vue
- web/vue.config.js
Example: \#123
- Add version & releases link;
- Remove connection button at the bottom;
- Modify some styles;
> feat(web): add version & releases link

- package.json
- src/version.ts
> chore(pkg): 1.8.0 -> 1.8.1

- src/background.ts
> fix(background): fix exited unexpectedly on macos

- cli/README-CN.md
- cli/README.md
- cli/src/index.ts
- cli/src/lib/conn.ts
Example: \#123
```shell
mqttx conn -h '34.219.25.208' --no-clean
```
> fix(cli): change clean to no-clean option

- .github/workflows/deploy_web.yaml
- web/src/router/index.ts
> fix(ci): fix deploy web CI failed issue

- cli/.prettierrc
- package.json
> chore(format): add web and cli code format

- .github/workflows/build_cli.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/deploy_web.yaml
- web/src/router/index.ts
> fix(ci): add cli build action and modify web action

- cli/README-CN.md
- cli/README.md
> docs(cli): update cli download links

- src/lang/connections.ts
- src/views/connections/ConnectionsDetail.vue
> fix(connection): fix $ symbol invalid

- cli/package.json
- package.json
- src/version.ts
- web/package.json
> chore(pkg): 1.8.1 -> 1.8.2

- src/main/updateChecker.ts
> fix(updater): replace download to install

- src/components/KeyValueEditor.vue
- src/views/connections/index.vue
> fix(properties): fix can not edit user properties

- src/database/database.config.ts
- src/database/migration/1659668384878-multiTopics.ts
- src/database/models/SettingEntity.ts
- src/store/getter.ts
- src/store/modules/app.ts
- src/types/global.d.ts
> feat(settings): add multi topics field

- src/background.ts
- src/components/SubscriptionsList.vue
- src/lang/settings.ts
- src/store/modules/app.ts
- src/views/settings/index.vue
> feat(subscriptions): support disable and enable multi-topics

- src/components/EmptyPage.vue
- src/components/Leftbar.vue
- src/lang/common.ts
- src/utils/gaCustomLinks.ts
- src/views/about/index.vue
…efer traffic
Example: \#123
Add parameters to URLs to identify the campaigns that refer traffic.
> chore(links): add parameters to URLs to identify the campaigns that refer traffic

- src/database/services/HistoryMessageHeaderService.ts
> fix(desktop): fix history message header update bug

- web/src/components/MsgPublish.vue
- web/src/database/index.ts
- web/src/utils/api/historyMessageHeaderService.ts
- web/src/utils/api/historyMessagePayloadService.ts
- web/src/utils/historyRecordUtils.ts
- web/src/views/connections/ConnectionsDetail.vue
> feat(web): add payload & topic history of sent messages

- web/src/components/Contextmenu.vue
- web/src/components/MsgPublish.vue
- web/src/lang/common.ts
- web/src/utils/api/connectionMessageService.ts
- web/src/views/connections/ConnectionsDetail.vue
- web/src/views/connections/ConnectionsList.vue
> feat(web): support message copy & message delete

- .github/workflows/build_cli.yaml
- cli/.dockerignore
- cli/.npmignore
- cli/Dockerfile
- cli/README-CN.md
- cli/README.md
- web/README-CN.md
- web/README.md
- web/public/index.html
Example: \#123
```shell
docker pull emqx/mqttx-cli
docker run -it --rm emqx/mqttx-cli
```
> feat(cli): add docker download

- .github/workflows/build_cli.yaml
- .github/workflows/deploy_web.yaml
> fix(docker): support for multiple platforms

- .github/workflows/deploy_web.yaml
- web/package.json
- web/vue.config.js
> feat(web): set the publicPath to '/' when building the docker image

- web/src/store/modules/app.ts
- web/src/views/connections/ConnectionsDetail.vue
> feat(web): add connect btn to topbar

- src/components/SubscriptionsList.vue
> fix(desktop): fix subscription color bug

- web/src/database/index.ts
- web/src/lang/settings.ts
- web/src/store/getter.ts
- web/src/store/modules/app.ts
- web/src/types/global.d.ts
- web/src/utils/mqttUtils.ts
- web/src/views/connections/ConnectionsDetail.vue
- web/src/views/connections/index.vue
- web/src/views/settings/index.vue
> feat(web): support auto resubscribe setting

- web/src/lang/connections.ts
- web/src/types/global.d.ts
- web/src/utils/mqttUtils.ts
- web/src/views/connections/ConnectionForm.vue
> feat(web): add reconnectPeriod option

- cli/src/index.ts
- cli/src/lib/sub.ts
- cli/src/utils/generator.ts
- cli/src/utils/parse.ts
\#1062
support multi-topic subscription
```bash
mqttx sub -t 'topic1' -t 'topic2' -h 'broker.emqx.io' -p 1883 -v
mqttx sub -t 'topic1' 'topic2' -h 'broker.emqx.io' -p 1883 -v
mqttx sub -t 'topic1' 'topic2' -h 'broker.emqx.io' -p 1883 -q 0 1 -v
```
> feat(cli): support multi-topic subscription

- cli/src/lib/pub.ts
> fix(cli): fix user properties option of pub command

- web/src/lang/connections.ts
- web/src/types/global.d.ts
- web/src/utils/mqttUtils.ts
- web/src/views/connections/ConnectionForm.vue
> feat(web): fully synchronized create connection form

- src/views/connections/ConnectionForm.vue
> improve(desktop): improve connection model

- cli/package.json
- cli/src/lib/conn.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
- cli/src/utils/signale.ts
- cli/tsconfig.json
- cli/yarn.lock
- src/utils/getFiles.ts
- web/src/utils/getFiles.ts
> feat(cli): improve logging

- cli/src/index.ts
- cli/src/utils/parse.ts
> feat(cli): add publish topic validation

- cli/package.json
- cli/src/index.ts
- package.json
- src/version.ts
- web/package.json
> feat(cli): add release note link to the output version command

- src/lang/common.ts
- src/lang/connections.ts
- src/utils/mqttUtils.ts
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionInfo.vue
> refactor(connection): clean session -> clean start on mqtt5

- src/lang/connections.ts
- src/utils/getFiles.ts
- src/utils/validFormatJson.ts
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionsDetail.vue
> refactor(connection): optimize ssl tls connection

- cli/src/index.ts
- cli/src/lib/conn.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
- cli/src/types/global.d.ts
- cli/src/utils/parse.ts
Example: \#123
Support more MQTT 5.0 properties.
> feat(cli): support more MQTT 5.0 properties

- src/views/connections/ConnectionsDetail.vue
> fix(connection): fix console error of timed message

- src/lang/script.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/script/index.vue
> fix(script): disabled delete in use script

- cli/src/index.ts
- cli/src/lib/conn.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
- cli/src/types/global.d.ts
- cli/src/utils/delay.ts
- cli/src/utils/signale.ts
- cli/tsconfig.json
Example: \#123
Add bench commands.
```bash
mqttx bench conn -c 5000
```
```bash
mqttx bench pub -c 5000 -t bench/%i -i 2
```
```bash
mqttx bench sub -c 5000 -t bench/%i -i 2
```
> feat(cli): add bench commands

- cli/src/lib/conn.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
> chore(cli): print error with client id

- web/src/views/connections/ConnectionForm.vue
> chore(web): remove certificates

- src/views/connections/ConnectionForm.vue
- web/src/views/connections/ConnectionForm.vue
> fix(connection): remove byte unit

- src/components/Leftbar.vue
- web/src/components/Leftbar.vue
> improve(leftbar): click outside close popover

- src/utils/sandbox.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/script/index.vue
\#1105
Add message type & index to script.
```ts
/**
* @description: default script
* @param {any} value - Payload
* @param {string} msgType - Message type, value is 'received' or 'publish'
* @param {number} index - Index of the message, vaild only when script is used in the publish message and timed message is enabled
* @return {any} - Payload after script processing
*/
function handlePayload(value, msgType, index) {
return value.msg
}
execute(handlePayload)
```
> feat(desktop): add message type & index to script

- cli/src/lib/sub.ts
> chore(cli): print retain flag

- src/utils/gaCustomLinks.ts
- src/views/help/index.vue
- web/src/utils/gaCustomLinks.ts
- web/src/views/help/index.vue
> chore(help): add utm params to links on help page

- src/components/Ipc.vue
- src/lang/menu.ts
- src/main/getMenuTemplate.ts
> feat(desktop): add shortcuts to new connections

- src/components/SubscriptionsList.vue
> styles(subs): change some sub list styles

- src/components/MsgPublish.vue
- src/components/ResizeHeight.vue
- src/views/connections/ConnectionsDetail.vue
> feat(connection): add hightlight for resize line when hover

- src/lang/settings.ts
- src/views/connections/ConnectionsDetail.vue
- web/src/lang/settings.ts
- web/src/views/connections/ConnectionsDetail.vue
> chore(resub): auto resub does not require clean session is true

- cli/README-CN.md
- cli/README.md
- cli/package.json
- package.json
- src/version.ts
- web/package.json
> chore(release): 1.8.3 -> 1.9.0

- cli/README-CN.md
- cli/README.md
- cli/src/index.ts
- cli/src/lib/conn.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
Example: \#123
Support auto reconnect for bench commands.
**conn**
**pub**
**sub**
> feat(cli): support auto reconnect for bench commands

- cli/src/lib/conn.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
> improve(cli): improve the output of the bench commands

- cli/src/index.ts
- cli/src/lib/conn.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
- cli/src/types/global.d.ts
- cli/src/utils/signale.ts
Example: \#123
Support set the maximum reconnect times.
> feat(cli): support set the maximum reconnect times

- cli/src/lib/conn.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
- cli/src/utils/signale.ts
> imporve(cli): optimize the code logic of the console logger

- cli/README-CN.md
- cli/README.md
- cli/src/index.ts
- cli/src/lib/sub.ts
- cli/src/types/global.d.ts
- cli/src/utils/convertPayload.ts
- cli/src/utils/parse.ts
- src/lang/connections.ts
- web/src/lang/connections.ts
> feat(cli): support payload format

- web/src/components/KeyValueEditor.vue
- web/src/types/global.d.ts
> fix(web): allow multiple occurrences of the same name in user properties

- cli/src/utils/config.ts
> feat(cli): validate config

- cli/README-CN.md
- cli/README.md
> docs(cli): modify readme

- src/database/services/MessageService.ts
- src/views/connections/ConnectionsDetail.vue
Example: \#123
Improves incoming message performance, separates message rendering and storage, and stores message data in bulk.
> improve(message): support batch rendering and storage messages

- src/components/ExportData.vue
- src/database/services/ConnectionService.ts
- src/store/modules/app.ts
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionInfo.vue
- src/views/connections/index.vue
> improve(desktop): remove vuex all connections data

- src/components/MsgPublish.vue
- src/lang/connections.ts
- src/views/connections/ConnectionsDetail.vue
Many new users don't know how to input a topic when they publish a message.
Example: #1055 
> refactor(topic): add topic input box prompt

- src/components/MsgPublish.vue
- src/database/services/ConnectionService.ts
- src/database/services/MessageService.ts
- src/views/connections/ConnectionForm.vue
- src/views/connections/ConnectionsDetail.vue
- web/src/components/Leftbar.vue
Example: \#123
-  Improve clearing history messages
- Close the menu bar after clicking on the copy option
- Modify the location of the read/write push prop method
> improve(desktop): improve clearing history messages

- src/components/SubscriptionsList.vue
- src/database/services/ConnectionService.ts
- src/database/services/SubscriptionService.ts
- src/database/useServices.ts
> improve(desktop): improve update subscriptions logic

- cli/package.json
- package.json
- src/version.ts
- web/package.json
> chore(pkg): upgrade version 1.9.1-beta.1

- src/assets/scss/element/element-reset.scss
- src/views/connections/ConnectionsDetail.vue
- src/views/settings/index.vue
> refactor(ui): ui/ue enhancement

- src/assets/scss/base.scss
- src/assets/scss/theme/dark.scss
- src/assets/scss/theme/light.scss
- src/assets/scss/theme/night.scss
- src/components/MsgPublish.vue
- src/components/SubscriptionsList.vue
- tsconfig.json
- web/src/assets/scss/base.scss
- web/src/assets/scss/theme/dark.scss
- web/src/assets/scss/theme/light.scss
- web/src/assets/scss/theme/night.scss
> fix(subs): unconnected alerts when clicking on new subscription

- src/views/about/index.vue
- web/src/views/about/index.vue
> chore(about): set copyright to automatically update

- src/views/connections/ConnectionsList.vue
- src/views/window/Window.vue
> fix(desktop): fix some bugs of the new window

- src/database/services/ConnectionService.ts
- src/database/services/MessageService.ts
- src/types/global.d.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/connections/index.vue
\#1131
Limit the amount of messages loaded to reduce page lag and memory consumption.
> improve(desktop): improve messages loading logic

- cli/package.json
- package.json
- src/version.ts
- web/package.json
> chore(pkg): upgrade version 1.9.1-beta.2

- src/database/services/MessageService.ts
- src/views/connections/ConnectionsDetail.vue
> improve(desktop): improve search message method

- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
- cli/src/utils/signale.ts
> feat(cli): display date

- src/utils/mqttUtils.ts
Fix bug where connection is not possible without filling in the username when client ID authentication is enabled.
> fix(desktop): fix connect bug

- src/views/connections/ConnectionsList.vue
> feat(desktop): add tooltip to connection group

- src/components/MsgTip.vue
> style(desktop): modify new message notification style

- src/store/modules/app.ts
- src/types/global.d.ts
- src/views/connections/ConnectionsDetail.vue
> improve(desktop): improve rendering message method

- src/components/MessageList.vue
- src/views/connections/ConnectionsDetail.vue
> fix(desktop): fix topic input foucs

- src/views/connections/ConnectionsList.vue
> fix(desktop): fix connections list highlight

- src/database/services/ConnectionService.ts
> fix(desktop): fix data import

- src/components/MsgPublish.vue
- web/src/components/MsgPublish.vue
Example: \#123
Let the user know that he has clicked the send button
> fix(msg): add active status on pub btn

- src/components/ExportData.vue
- src/database/services/ConnectionService.ts
> fix(desktop): fix the issue of lost message data in exporting data

- src/components/SubscriptionsList.vue
- src/utils/getContextmenuPosition.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/connections/ConnectionsList.vue
> fix(desktop): fix contextmenu position

- src/components/SubscriptionsList.vue
> fix(desktop): fix subscribe form reset fields

- cli/package.json
- package.json
- src/version.ts
- web/package.json
> chore(pkg): upgrade version 1.9.1

- src/components/Editor.vue
> fix(editor): fix edtior not adapted to window resizing

- src/components/ImportData.vue
- src/database/services/ConnectionService.ts
> improve(desktop): refactor data import logic

- src/components/ImportData.vue
> style(desktop): modify some styles of the import data tip

- cli/README-CN.md
- cli/README.md
> docs(cli): update readme

- package.json
- yarn.lock
> chore(pkg): fixed vm version

- src/components/MsgPublish.vue
- web/src/components/MsgPublish.vue
> improve(desktop): add title attribute to history topic

- cli/src/utils/parse.ts
- src/utils/mqttUtils.ts
> refactor(mqtt): improve code readability

- README-CN.md
- README-JP.md
- README.md
> chore: update readme

- cli/package.json
- package.json
- src/version.ts
- web/package.json
> chore(pkg): upgrade version 1.9.2

- src/assets/scss/base.scss
> fix(message): fix break word styles

- src/components/SubscriptionsList.vue
- src/utils/mqttUtils.ts
> fix(mqtt): fix the issue with password validation

- src/types/global.d.ts
> fix(type): remove useless type define

- web/package.json
- web/src/main.ts
- web/src/router/index.ts
- web/yarn.lock
> feat(gtm): add google tag manager

- README-CN.md
- README-JP.md
- README.md
- cli/README-CN.md
- cli/README.md
- web/README-CN.md
- web/README.md
> refactor: fix shields icon name to MQTTX

- src/utils/mqttUtils.ts
- web/src/utils/mqttUtils.ts
> fix(connections): set auto reconnect to true by default

- src/views/connections/ConnectionsDetail.vue
- web/src/views/connections/ConnectionsDetail.vue
> fix(connections): disable edit in connecting status

- cli/README-CN.md
- cli/README.md
- cli/src/index.ts
> docs(cli): update readme of simulate

- cli/package.json
- package.json
- src/version.ts
- web/package.json
> chore(pkg): upgrade version 1.9.3

- cli/src/lib/pub.ts
- cli/src/scenarios/IEM.ts
- scripts-example/IoT-data-scenarios/IEM.js
- scripts-example/IoT-data-scenarios/tesla.js
Example: \#123
Add a new scenario to simulate: Industrial Energy Monitoring (IEM) for generating energy consumption data for factory production lines, serving the IIoT.
> feat(simulate): add industrial energy monitoring scenario script

- cli/src/scenarios/IEM.ts
- cli/src/scenarios/smart_home.ts
- cli/src/scenarios/tesla.ts
- cli/src/scenarios/weather.ts
- scripts-example/IoT-data-scenarios/IEM.js
- scripts-example/IoT-data-scenarios/smart_home.js
- scripts-example/IoT-data-scenarios/tesla.js
- scripts-example/IoT-data-scenarios/weather.js
Example: \#123
```shell
mqttx simulate -sc weather
```
> feat(cli): add weather scenario

- src/utils/gaCustomLinks.ts
- web/src/utils/gaCustomLinks.ts
> docs(help): modify mqtt page link

- docs/manual.md
Update the `manual.md` with Grammarly
No
> docs(manual): review and update manual.md with Grammarly

- src/background.ts
- src/main/updateChecker.ts
- src/main/updateDownloader.ts
- src/views/Home.vue
- src/views/update/index.vue
1. If the new version is not installed, just click Install and cancel, the next startup will still display the update information window。
2. The dark mode style is not correct
3. Components are not set to load asynchronously, which may affect startup speed
4. The dialog is too small
None
> fix(update):fix update bugs

- web/src/App.vue
In the web version, right mouse click to display the browser menu
Block browser right-click events
> fix(web):prevent right click default event

- cli/src/lib/conn.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
Incorrect number of connections displayed
Show the correct number of connections
> fix(cli):fix the incorrect count

- src/components/SubscriptionsList.vue
- src/views/connections/ConnectionsList.vue
- web/src/App.vue
- web/src/components/SubscriptionsList.vue
Disable global context menu
Disable the right-click browser menu for only some components
> fix(contextmenu):prevent contextmenu default events

- cli/src/utils/checkUpdate.ts
Using github's api has certain restrictions on api and access
Using the api of mqttx.app, the response speed is faster, and no ip and access restrictions
> fix(update):modify cli update url

- cli/src/lib/pub.ts
- cli/src/utils/protobuf.ts
> fix(cli):optimize error handling

- cli/package.json
- cli/src/utils/config.ts
- cli/yarn.lock
The [yaml.js](https://github.com/jeremyfa/yaml.js) library has not been maintained and updated for many years .
1. replaced yaml.js with js-yaml
> chore(cli):replaced yaml.js with js-yaml

- src/views/script/index.vue
> style(script):add script-output bottom padding

- src/utils/sandbox.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/script/index.vue
> fix(script):function script error handling

- src/lang/connections.ts
> fix(connections): completed i18n

- src/assets/scss/mixins.scss
- web/src/assets/scss/mixins.scss
> style(message): modify the message max width

- src/components/MsgPublish.vue
- src/utils/validFormatJson.ts
- src/views/connections/ConnectionsDetail.vue
> fix(connection):fix vaild-format-json error

- .github/workflows/build_cli.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/deploy_web.yaml
> feat(ci): upload packages to aws s3

- src/main/updateChecker.ts
- src/main/updateDownloader.ts
- src/views/Home.vue
1. Opening MQTTX takes too long time to initialize
2. The changelog window displays a white screen
#1370 
1. Lazy update detection and component loading
2. The update window appears only when the network is connected
> improve(upodate):lazy update detection and component loading

- src/components/MsgLeftItem.vue
- src/utils/validFormatJson.ts
- src/views/connections/ConnectionsDetail.vue
> improve(msg-left-item):add msg type meta props

- src/components/MsgLeftItem.vue
- src/views/script/index.vue
> fix(script): adapt the tabs border color to dark mode

- cli/package.json
- package.json
- src/version.ts
- web/package.json
> chore(pkg): upgrade version 1.9.5

- .github/workflows/build_packages.yaml
> chore(ci): fix can not cp to aws s3

- .github/workflows/build_packages.yaml
> chore(ci): fix aws s3 upload cli

- src/components/MsgPublish.vue
- src/lang/connections.ts
- src/utils/element.ts
- src/views/connections/ConnectionsDetail.vue
- web/src/components/MsgPublish.vue
- web/src/components/SubscriptionsList.vue
- web/src/lang/connections.ts
- web/src/utils/element.ts
- web/src/views/connections/ConnectionsDetail.vue
> refactor(publish): optimize publish options UI

- cli/package.json
- package.json
- src/components/MsgLeftItem.vue
- src/components/MsgPublish.vue
- src/lang/connections.ts
- src/version.ts
- src/views/connections/ConnectionsDetail.vue
- web/package.json
- web/src/components/MsgLeftItem.vue
> feat(msg): simplify clear retained message operation

- .github/workflows/deploy_web.yaml
Insecure download with http.
none
Use secure https.
none
none
> fix(CI): change download to secure https://

- src/components/MsgPublish.vue
- web/src/components/MsgPublish.vue
> fix(publish): remove unuse placeholder

- src/components/SubscriptionsList.vue
- src/lang/connections.ts
- web/src/components/SubscriptionsList.vue
- web/src/lang/connections.ts
> fix(clients): update translation for nl rap and rh

- apps/desktop/package.json
- pnpm-lock.yaml
> chore(pkg): bump electron version to v27.0.2 @ysfscream

- apps/desktop/tsconfig.web.json
- apps/web/tsconfig.app.json
- packages/tsconfig/base.json
- packages/tsconfig/types.json
- packages/ui/src/components/connections/ListView.vue
- packages/ui/src/index.ts
- packages/ui/tsconfig.json
https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax
> feat(tsconfig): enable verbatimModuleSyntax

- apps/desktop/package.json
- apps/desktop/src/renderer/src/env.d.ts
- apps/desktop/src/renderer/src/main.ts
- apps/desktop/src/renderer/src/pages/connections/Details.vue
- apps/desktop/src/renderer/src/pages/connections/Index.vue
- apps/web/env.d.ts
- apps/web/package.json
- apps/web/src/main.ts
- apps/web/src/pages/connections/Details.vue
- apps/web/src/pages/connections/Index.vue
- packages/ui/package.json
- packages/ui/src/components/connections/ListView.vue
- packages/ui/src/index.ts
- packages/ui/src/stores/index.ts
- packages/ui/src/stores/useConnectionsStore.ts
- packages/ui/src/stores/useSettingsStore.ts
- pnpm-lock.yaml
> feat(ui): add shared store

- .husky/pre-commit
- lint-staged.config.js
- package.json
- pnpm-lock.yaml
> feat(*): add husky & lint-staged

- package.json
> fix(pkg): add husky init script command

- apps/desktop/src/main/index.ts
- packages/types/base.ts
- packages/ui/src/components/common/LeftBar.vue
- packages/ui/src/stores/useSettingsStore.ts
- packages/ui/src/styles/variable.scss
> feat(types): add theme type define

- apps/desktop/src/renderer/src/pages/connections/Index.vue
- apps/web/src/pages/connections/Index.vue
- packages/ui/src/components/common/SplitView.vue
- packages/ui/src/components/connections/DetailsView.vue
- packages/ui/src/components/connections/ListView.vue
- packages/ui/src/index.ts
- packages/ui/src/styles/connections.scss
> feat(ui): add split view component

- apps/desktop/src/renderer/src/pages/connections/Index.vue
- apps/web/src/pages/connections/Index.vue
- packages/ui/src/components/common/LeftBar.vue
- packages/ui/src/components/common/SplitView.vue
- packages/ui/src/components/connections/DetailsView.vue
- packages/ui/src/components/connections/ListView.vue
- packages/ui/src/styles/connections.scss
The page now allows dragging to adjust the width and height of panels @Red-Asuka
> feat(ui): add hover styles to split view

- apps/desktop/src/renderer/src/App.vue
- apps/web/src/App.vue
- packages/ui/src/components/common/LeftMenu.vue
- packages/ui/src/index.ts
> refactor(ui): rename the leftbar to leftmenu

- .github/workflows/build_cli.yaml
- .github/workflows/build_packages.yaml
- .github/workflows/deploy_web.yaml
- .github/workflows/unit_tests.yaml
> chore(ci): add run test action

- .github/workflows/deploy_web.yaml
> chore(ci): modify the build web ci

- .github/workflows/build_cli.yaml
- .github/workflows/build_desktop.yaml
- .github/workflows/deploy_web.yaml
- packages/core/tsconfig.json
- packages/ui/tsconfig.json
- packages/ui/vite.config.ts
> chore(ci): modify the build desktop ci

- .github/workflows/build_desktop.yaml
> fix(ci): add paths for desktop app in pull_request event

- package.json
- src/assets/scss/element/element-reset.scss
- src/components/Copilot.vue
- src/lang/common.ts
- src/types/global.d.ts
- src/types/shims-vue.d.ts
- src/views/connections/ConnectionsDetail.vue
- yarn.lock
> feat(copilot): add mqttx copilot

- package.json
- src/background.ts
- src/components/Copilot.vue
- src/database/database.config.ts
- src/database/migration/1701761407723-aiSettings.ts
- src/database/models/SettingEntity.ts
- src/lang/common.ts
- src/lang/settings.ts
- src/store/getter.ts
- src/store/modules/app.ts
- src/types/global.d.ts
- src/types/shims-vue.d.ts
- src/utils/idGenerator.ts
- src/views/settings/index.vue
- yarn.lock
> feat(settings): add api key and model fields to database

- src/assets/scss/base.scss
- src/components/Copilot.vue
- src/components/SubscriptionsList.vue
- src/lang/common.ts
- src/utils/idGenerator.ts
- src/views/connections/ConnectionsDetail.vue
- src/views/settings/index.vue
> feat(copilot): support onclick to ask and analyze error msg

- src/utils/mqttUtils.ts
> fix(connections): fix can send empty auth info

- src/components/Copilot.vue
- src/components/PresetPromptSelect.vue
> feat(copilot): add preset prompt select component

- src/components/Copilot.vue
- src/utils/copilot.ts
> feat(copilot): stream response support

- src/lang/common.ts
- src/views/connections/ConnectionsDetail.vue
- yarn.lock
> feat(copilot): take connection info when ask error prompt

- src/components/Copilot.vue
https://platform.openai.com/docs/api-reference/chat/create#chat-create-temperature
As an MQTT assistant, accuracy is required.
> fix(copilot): update temp value in openai api

- src/assets/scss/theme/custom/prism-one-dark.scss
- src/assets/scss/theme/custom/prism-one-light.scss
- src/background.ts
- src/components/Copilot.vue
- src/components/Ipc.vue
- src/components/MsgLeftItem.vue
- src/components/MsgPublish.vue
- src/components/PresetPromptSelect.vue
- src/lang/common.ts
- src/store/getter.ts
- src/store/modules/app.ts
- src/types/global.d.ts
- src/views/connections/ConnectionsDetail.vue
> feat(copilot): add copy and insert button in code block

- cli/package.json
- cli/src/index.ts
- cli/src/lib/conn.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
- cli/src/types/global.d.ts
- cli/yarn.lock
> feat(cli): add support debug mode with mqttjs

- cli/src/types/global.d.ts
> fix(cli): omit debug type in bench types

- web/src/lang/connections.ts
- web/src/views/connections/ConnectionsDetail.vue
> feat(web): add disconnect event

- cli/package.json
- cli/src/index.ts
- cli/src/lib/pub.ts
- cli/src/lib/sub.ts
- cli/src/types/global.d.ts
- cli/src/utils/convertPayload.ts
- cli/src/utils/parse.ts
- cli/yarn.lock
> feat(cli): cbor format support

- src/components/Editor.vue
> fix(desltop): fix editor layout issue when conn-list visible change

- src/assets/scss/connections.scss
- src/views/connections/index.vue
- src/views/window/Window.vue
> fix(desktop): fix can not hide the conn-list in new window

- src/components/Copilot.vue
- src/components/PresetPromptSelect.vue
- src/lang/common.ts
> refactor(copilot): add more category code generators

- README.md
> docs(readme): update link

- src/database/services/MessageService.ts
> fix(desktop): fix the bug of topic filtering

- yarn.lock
Fix build error in CI issue #1647.
> chore(desktop): replace nlark.com to npmjs.org

- src/types/global.d.ts
- src/views/settings/index.vue
> feat(copilot): gpt-4o support

- cli/src/utils/signale.ts
> refactor(cli): improve logging format

- .github/workflows/deploy_web.yaml
- web/.env
> chore(ci): modify web deploy

- cli/src/configs/init.ts
- cli/src/index.ts
> feat(cli): support init and load config file

- cli/src/configs/common.ts
- cli/src/index.ts
- cli/src/state/index.ts
- cli/src/types/global.d.ts
- cli/src/utils/fileUtils.ts
- cli/src/utils/signale.ts
> feat(cli): apply the config file

- cli/src/utils/checkUpdate.ts
> feat(cli): improve check update with ora

- cli/src/utils/logWrapper.ts
> refactor(cli): gray the output meta info

- web/src/views/about/index.vue
> fix(links): emqx.io -> emqx.com

- .github/workflows/build_cli.yaml
> chore(cli_ci): upgrade the node version to 18

- web/src/views/connections/ConnectionForm.vue
- web/src/views/connections/ConnectionsDetail.vue
> docs(web): update migration announcement link

- web/README-CN.md
- web/README.md
> docs(web): update online usage link

- src/main/installCLI.ts
1. Windows cannot execute mqttx cli on the terminal, making it hard to check the current mqttx CLI version, so we skip the check directly.
2. Users need to manually download the mqttx CLI on Windows, allowing them to select the download path to use mqttx.exe.
> feat(desktop): skip cli version check on windows

- src/views/connections/ConnectionsDetail.vue
- web/src/views/connections/ConnectionsDetail.vue
> fix(desktop): fix the style issue of connection name

- cli/src/__tests__/utils/convertPayload.test.ts
> test(cli): convert paylaod test case support

- cli/src/__tests__/utils/avro.test.ts
- cli/src/__tests__/utils/mockData/mockProto.proto
- cli/src/__tests__/utils/protobuf.test.ts
> test(cli): add protobuf test cases

- cli/src/lib/sub.ts
> fix(cli): remove bench sub topics log

- .github/workflows/build_cli.yaml
- cli/package.json
- cli/src/__tests__/utils/parse.test.ts
- cli/src/index.ts
- cli/src/utils/parse.ts
- cli/yarn.lock
> feat(cli): message pack format support

- src/components/charts/TreeVisual.vue
- src/components/widgets/TreeView.vue
> fix(desktop): fix tooltip overflow in tree visual component

- src/assets/scss/base.scss
- src/components/widgets/TreeNodeInfo.vue
> fix(desktop): optimize scrollbar corner style in topic tree

- package.json
- pnpm-lock.yaml
- turbo.json
> chore(deps): update turbo from 1.10.16 to 2.2.3

- apps/desktop/package.json
- apps/desktop/src/main/index.ts
- pnpm-lock.yaml
Introduced Vue.js devtools to facilitate debugging in the development environment.
> [!NOTE]  
> A manual page refresh is required to properly load the plugin: https://github.com/vuejs/devtools-v6/issues/901
> feat(desktop): add electron-devtools-installer for Vue.js debugging support

- .github/workflows/build_desktop.yaml
- apps/desktop/package.json
- apps/desktop/src/database/schemas/encryption.ts
- apps/desktop/src/database/schemas/settings.ts
- apps/desktop/src/renderer/src/env.d.ts
- apps/desktop/tsconfig.node.json
- pnpm-lock.yaml
The keys are stored in plaintext in the code, requiring manual decryption before use.
Example: \#123
The keys have been moved to GitHub Actions. Decryption is now automated using the customType feature of Drizzle.
> feat(desktop): implement encryption for OpenAI API key

- .github/workflows/deploy_web.yaml
- apps/desktop/src/database/schemas/encryption.ts
- apps/desktop/src/renderer/index.html
- apps/web/env.d.ts
- apps/web/src/database/index.ts
- Fix the issue of Desktop database migration failure
- Change the Web database password to be configured using the env file, and load it through GitHub Action in the production environment
- Fix the error of Desktop image loading
> fix(desktop): fix database migration error

- apps/desktop/package.json
- apps/desktop/src/main/index.ts
- pnpm-lock.yaml
- Enhanced development experience by supporting shortcuts to open developer tools.
- Fixed the bug where Vue DevTools required a refresh to display correctly.
> feat(desktop): add electron-debug for improved development experience

- apps/desktop/src/database/schemas/settings.ts
- apps/desktop/src/main/config/index.ts
- apps/desktop/src/main/config/windowState.ts
- apps/desktop/src/main/index.ts
- Window width and height are recorded in a database table.
- Only window size can be restored, but position and fullscreen status cannot be recovered.
- Use store to record window dimensions.
- Add boundary check to ensure the window is within a visible area.
- Record fullscreen status.
> improve(desktop): improve window state management

- babel.config.js
- src/components/Copilot.vue
- vue.config.js
> fix(copilot): fix loading state

- src/components/Copilot.vue
- src/components/PresetPromptSelect.vue
- src/lang/common.ts
- src/views/Home.vue
- src/views/connections/ConnectionsDetail.vue
- src/views/connections/index.vue
- src/views/script/index.vue
- tests/unit/utils/messageQueue.spec.ts
- Change Copilot modal from being linked to specific pages to being a global modal.
- Improve the style of the response content from Copilot.
- Support generating preset scripts.
- Support generating custom scripts based on user input requirements.
- Remove the record parameter and fetch it from the parent component.
> feat(copilot): support generating custom functions

- src/lang/common.ts
- src/views/script/index.vue
- Enhanced prompts for generating custom functions.
- Improved button styling for the Copilot on the script page.
> style(copilot): update copilot button icon and enhance styling

- src/components/Copilot.vue
- src/components/PresetPromptSelect.vue
- src/lang/common.ts
- src/utils/protobuf.ts
- src/views/script/index.vue
Support for generating custom or preset schemas.
> feat(copilot): support generating schema

- src/components/ai/Copilot.vue
- src/utils/ai/SessionManager.ts
- tests/unit/utils/ai/SessionManager.spec.ts
- tests/unit/utils/ai/copilot.spec.ts
Currently, the Copilot component handles both UI interactions and session management responsibilities, violating the single responsibility principle. This makes the codebase harder to maintain, test, and extend as the functionality grows.
Refactored the codebase to separate concerns by:
1. Creating a dedicated `SessionManager` class that handles all session-related logic including:
- Session state management
- System prompt loading
- Session lifecycle operations
2. Modified the Copilot component to use the new SessionManager, focusing it solely on UI interactions and user experience.
3. Properly defined interfaces and types to ensure type safety throughout …
> feat(copilot): introduce session management for AI interactions

- src/components/ai/Copilot.vue
- src/components/ai/CopilotInput.vue
- src/components/ai/MessageRender.vue
- src/utils/ai/AIAgent.ts
- src/utils/ai/mcp/MCPUtils.ts
Currently, AI interaction logic is directly embedded in the Copilot.Vue component, making it difficult to reuse and mix multiple responsibilities. All model calls, response handling, state management, and MCP processing are concentrated in the same component, resulting in a bloated component that cannot reuse the same AI interaction functionality in other scenarios.
Example: #123
1. **Extracted AI interaction logic**: Created an independent `AIAgent` class that encapsulates all core functionality for interacting with large language models:
- Message history construction
- Streaming response handling
- MCP tool call processing
- Error handling and …
> refactor(copilot): integrate AI Agent for response handling

- src/components/ai/Copilot.vue
- src/components/ai/MessageRender.vue
- src/database/services/CopilotService.ts
- src/lang/copilot.ts
- src/types/copilot.ts
- src/utils/ai/AIAgent.ts
- src/utils/ai/copilot.ts
- src/utils/ai/prompts/mcpResultAnalysis.txt
After executing an MCP call, the system only displays the raw results without further analysis. This requires users to interpret the data themselves, which can be challenging for complex results.
Implemented Chat Loop functionality according to MCP documentation. After executing an MCP call, the AI model now analyzes the results, providing users with more meaningful insights and interpretations. The implementation:
- Adds a conversation loop that processes MCP results using the AI model
- Includes proper stopping conditions using the "[DONE]" marker
- Cleans up the presentation by removing technical markers from the final output
- Improves user experience …
> feat(copilot): implement MCP result processing

- src/background.ts
- vue.config.js
Fix these errors: https://github.com/emqx/MQTTX/actions/runs/14089434360
> fix(desktop): fix generate the latest.yaml issue on ci

- .github/workflows/build_packages.yaml
- vue.config.js
Fix https://github.com/emqx/MQTTX/actions/runs/14090127644
> fix(ci): update artifact upload process to use gitHub release

- package.json
- src/utils/ai/copilot.ts
- yarn.lock
Example: None
https://openai.com/index/gpt-4-1/
> chore(deps): update @ai-sdk/openai to support gpt-4.1

- src/components/MessageList.vue
- src/components/ai/CopilotMessages.vue
> fix(desktop): fix sys scrollbar style issue for win

- src/utils/ai/copilot.ts
- tests/unit/utils/ai/copilot.spec.ts
> feat(copilot): claude-4 llm model support

- package.json
- src/utils/ai/AIAgent.ts
- src/utils/ai/copilot.ts
- tests/unit/utils/ai/copilot.spec.ts
- yarn.lock
> feat(copilot): gemini 2.5 thinking mode support
