emqx/MQTTX

src/utils/mqttUtils.ts, src/views/connections/ConnectionForm.vue
Because the use of these two properties needs to be redesigned.
=> refactor(connection): remove requestResponse properties

src/lang/connections.ts, src/utils/mqttUtils.ts, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionInfo.vue, src/views/connections/types.ts
Feature realization:
* Support append timestamp to MQTT client ID, which prevent duplicate connections.
* Add floating tips to explain what the client ID timestamp button does.
The timestamp of the attachment will not be displayed on the connection interface, but will be attached to the clientID when actually connecting.
And two connections with the same client ID will exist at the same time due to attachment time.(Actually not the same clientID)
[https://github.com/emqx/MQTTX/issues/394#event-4082449360](https://github.com/emqx/MQTTX/issues/394#event-4082449360)
=> feat(connection): support append timestamp to MQTT client id.

src/views/connections/ConnectionInfo.vue
The following is the previous version:
We expect that the form cannot be modified when connected, Now we cannot modify the form while connected.
=> feature(connections): disable ConnectionInfo table editing when client was connected

src/views/connections/ConnectionForm.vue
The old version of the input component will have a length when you click the plus and minus buttons, use el-input-number instead.
=> fix(UI): fixed the jitter of the input component

docs/manual-cn.md, docs/manual-jp.md, docs/manual.md, package.json, src/main.ts, src/utils/logger.ts
when we close the MQTTX in the windows, it shows something error like:
```
Uncaught Exception:
Error: EINVAL: invalid argument, rename
‘C:\Users\MYUSERNAME\AppData\Roaming\MQTTX/logs/log' ->
'C:\Users\MYUSERNAME\AppData\Roaming\MQTTX/logs/log/2021-01-29T1948.log'
```
#491 
I rewrite the logger part, it works also in the windows platform without any error report.
None.
=> fix(logs): fix windows filename error & build error

package.json, src/background.ts, yarn.lock
Cannot load normally when running electron:serve command.
In some scenarios, an exception occurs when MQTTX decompresses the `crx` file. APP launch failed.
None
launch APP normally.
ref: [https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-rc.4](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-rc.4)
=> fix(cli): fix launch electron failed becauseof vue-cli-plugins updates

src/components/MsgPublish.vue
When we jump from the `creation` page to `log/script` page, the editor ref `undefined`. Error occurs.
None.
Deal with editor create and destroy when jumping to `creation` from `connection`, and do nothing otherwise.
None
=> fix(MsgPulish): fix editorRef invalidation becauseof route params undefined

.github/PULL_REQUEST_TEMPLATE.md, src/views/connections/ConnectionsDetail.vue
When the title name is too long, there is a problem with the page layout.
#493 
When the title name of the top bar is too long, omit part of it, and then an ellipsis appears.
=> style(connection): fix the layout disorder caused by the long name

src/views/connections/ConnectionsDetail.vue
If we send a message with checked the `test` topic filter, and send the topic `testtopic/1` with the message, the log message won't record.
How to recurrent
click send button:
We can't find the message send record after clicking the send button:
unless we are in the right topic, the topic send log will not record.
None.
Whatever topic filter you are checked, we will get the message log record.
=> fix(logs): fix can't record log message when we send in other filter

src/views/connections/ConnectionsDetail.vue
When the MQTT broker is actively disconnected, the panel will not expand. At this time, you cannot see the connection button and you cannot quickly connect.
#509
Add a CONNECT button in the top bar when the collapsed panel is not expanded.
=> feat(connection): support quick connection when the panel is folded

src/components/MsgPublish.vue, src/views/connections/ConnectionsDetail.vue
When we jump order by `other page` -> `creation page` -> `connection page`, and press on `ctrl/cmd` + `enter`, we will get two message.
I hold the view that it caused by the `editor` init early when we jump from `other page` to `creation page`, so we init two`editor`s here.
We should destroy the early init `editor`  component, like before we do: #446 
Here is my solution:
Spy on the router, when we jump from `other page` to `creation page`, we just destroy the editor which init in `MsgPublish`.
None:
When we follow jump order by `other page` -> `creation page` -> `connection page`, and press on `ctrl/cmd` + `enter`, we will get only one message.
=> fix(MsgPublish): fix editor error when router jump from other page to creation & connection

src/components/SubscriptionsList.vue, src/lang/connections.ts
Signed-off-by: oceanlvr <657531018@qq.com>
when we deny any sub in `emqx` ACL rules, and use `MQTT X` sub any topic will get prompt : `$SYS reject`.
#527 
If we sub `MQTT Broker`, and get deny, there should be prompt 
`Unexpected QoS, SubACK failed, Please check MQTT broker configuration`
and when we sub $sys topic will get :  
`Rejected the $SYS topic,Unexpected QoS, MQTT Broker declined the subscription. Please check ACL configuration`
=> fix(subscription): fix SYS topic reject prompt error

src/assets/scss/theme/dark.scss, src/assets/scss/theme/light.scss, src/assets/scss/theme/night.scss, src/components/SubscriptionsList.vue, src/main.ts
When you click on the topic name, the tooltip will show the successfully copied content and then disappear automatically
None
Optimize the tips for copying Topic information. Tooltip will not automatically disappear if the copied content appears
=> fix(subs): fix copy topic and tooltip disappears

src/views/connections/ConnectionsList.vue, src/views/connections/index.vue
highlight issue like:
1. click a connection `A`
2. click another connection `B`
3. connection current connection
4. the  highlight connection is `A`(expect highlight `B`)
None.
Lead to the `current-node-key` is not reactive, so it won't change like  we expect.
ref issue: https://github.com/ElemeFE/element/issues/17246
=> fix(connecionsList): fix connection hightlight incorrect issue

src/store/getter.ts, src/store/modules/app.ts, src/types/global.d.ts, src/views/connections/ConnectionsList.vue, src/views/connections/types.ts
connect action makes `connectionsList` refresh, which leads to loss of the expanded state information.
None
support collection expanded state management.
https://user-images.githubusercontent.com/36698124/115832595-a69df300-a445-11eb-9cd8-2683109b99b4.mp4
=> feat(connecionsList): add collection expanded state management

src/components/MsgPublish.vue
None.
https://github.com/emqx/MQTTX/issues/455
support quick select message header:
check one option it will be auto-complete the `payload` `topic` `retain` options.
and when we send a message with a new header, this option will be added to the selector item.(max item number is 10 now).
=> feat(Msgpublish): support select message header by selector

src/components/MsgPublish.vue
The historical payload can be obtained, but the payload type cannot be set
Example: None
Payload Type should be consistent with Payload when switching history.
=> fix(msg): fix payload type can not restored

README-CN.md, package.json, vue.config.js, yarn.lock
=> chore(deps): bump vue-cli-plugin-electron-builder from 1.4.6 to 2.0.0

src/views/connections/ConnectionsList.vue
After clicking the new collection button, you need to manually focus on the input.
Example: none
After clicking the new collection button, the input is automatically focused
=> feat(connection): auto focus on new collection input

src/components/SubscriptionsList.vue, src/types/global.d.ts, src/utils/mqttUtils.ts, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionsDetail.vue, src/views/connections/index.vue, src/views/window/Window.vue
Every connection model has a client property.
Example: None
Remove client on connection.
=> refactor(connection): remove client property on connection model

src/background.ts, src/database/services/SettingService.ts, src/database/useConnection.ts, src/main.ts
=> refactor(settings): refactor settings service

src/components/MessageList.vue, src/components/MsgPublish.vue, src/database/models/CollectionEntity.ts, src/database/models/ConnectionEntity.ts, src/database/models/HistoryMessageHeaderEntity.ts, src/database/models/HistoryMessagePayloadEntity.ts, src/database/models/MessageEntity.ts, src/database/models/ScriptEntity.ts, src/database/models/SubscriptionEntity.ts, src/database/models/WillEntity.ts, src/database/services/ConnectionService.ts, src/database/services/MessageService.ts, src/types/global.d.ts, src/views/connections/ConnectionsDetail.vue
=> refactor(entity): refactor model types

src/api/connection.ts, src/components/ExportData.vue, src/database/models/ConnectionEntity.ts, src/database/services/CollectionService.ts, src/types/global.d.ts, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionsList.vue, src/views/connections/index.vue, src/views/window/Window.vue
=> fix(service): fix collection service set get API

src/api/connection.ts, src/components/ClearUpHistoryData.vue, src/components/ImportData.vue, src/components/MsgPublish.vue, src/components/SubscriptionsList.vue, src/database/models/WillEntity.ts, src/database/services/ConnectionService.ts, src/database/services/SettingService.ts, src/utils/connections.ts, src/utils/mqttUtils.ts, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionInfo.vue, src/views/connections/ConnectionsDetail.vue, src/views/connections/ConnectionsList.vue, tsconfig.json
=> refactor(service): refactor connection & history service

src/components/MessageList.vue
The left message color bar was hidden by `vue-recycle-scroller`.
None.
remove the hidden rule.
=> fix(message): fix leftItem color bar display issue

src/components/MessageList.vue, src/components/MsgLeftItem.vue, src/types/global.d.ts
Lost left message color bar.
`vue-virtual-scroller` can't use state component originally, typescript with vue-class is incompatible well with `vue-virtual-scroller` 
reference: 
* https://github.com/Akryum/vue-virtual-scroller#idstate
* https://github.com/Akryum/vue-virtual-scroller/issues/513
=> fix(messageItem): fix left message item data state render issue

src/components/MsgPublish.vue
#705 
Enter the binary data, MQTTX exit, and then reopen. Binary data format remains unchanged
The cause of the problem is that it is already binary when it is opened, and it is caused by re-encoding.
Change the data type before obtaining the historical information, so that the first entry will not be re-encoded
=> fix(msgPublish): Data format conversion error

src/components/SubscriptionsList.vue, src/database/services/ConnectionService.ts
Example: \#123
I think the reason is the sync problem between connection / subscribe  (resubscribe) /  messageArrive event.
so delay subscribing (resubscribe), maybe a better way, which makes the sub-event behind the on message arrives.
=> fix(subscribe): fix retain message flash/mis-render issue

src/database/services/HistoryMessageHeaderService.ts, src/database/services/HistoryMessagePayloaderService.ts, src/utils/mqttUtils.ts, src/views/connections/ConnectionsDetail.vue
Incorrect message compare algorithm & `get` / `set` history service API
Reference PR: #716 
Enhance history query with time field.
=> fix(history): fix history message record issue

src/database/models/HistoryConnectionEntity.ts, src/database/services/ConnectionService.ts
Fetch history connection record without `id` field.
Example: \#123
=> fix(connectionHistory): history connection duplication id issue

src/database/services/ConnectionService.ts
1. update a connection state in the `connectionList` part, such as dragging the connection to anthor collection.
2. update data in the `connectionDetail` part, such as connect the connection.
3. fetch the not the latest state in `connectionDetail` updated by `connectionList` part.
Then `connectionDetail` has will update the older data which `connectionList` has been updated. 
Example: \#123
=> fix(connectionList): unexpected collectionId update issue

src/database/migration/1635393164071-huLang.ts, src/database/services/ConnectionService.ts, src/views/connections/ConnectionForm.vue, src/views/connections/index.vue
unsuccess mqtt5 connection.
Example: \#123
直接新建连接能够成功连接到 mqtt5 因为 mqtt5 props 字段为空，即加载了默认值。不会导致错误
而在路径新建 -> 连接 -> 修改页 -> 连接 的路径下，加载了 receiveMaximum 最小值 min = 0 导致了错误。
其合法最小值为 1
=> fix(mqtt5): update receiveMaximum initial value

src/components/MsgPublish.vue, src/views/connections/ConnectionsDetail.vue
=> WIP: add push mqtt5 props card

src/components/MsgPublish.vue, src/database/database.config.ts, src/database/migration/1638375518392-messageHistoryProps.ts, src/database/models/ConnectionEntity.ts, src/database/services/MessageService.ts, src/types/global.d.ts, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionsDetail.vue
=> feat(message): support message push prop history

src/components/MsgPublish.vue, src/views/connections/ConnectionsDetail.vue
=> fix(msg): fix save properties issue

src/types/global.d.ts, src/utils/mqttUtils.ts, src/views/about/index.vue, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionsDetail.vue
Will trigger two resub.
Example: none
@oceanlvr PTAL
Auto resub is a global state that should not be present in the connection. Make sure that resubscribing only triggers once
=> fix(connection): fix sync auto resub issue

src/views/connections/ConnectionsDetail.vue
There seems to be a problem with mqttx1.7 persistent sessions, if the client is disconnected and reconnected, the messages received during the offline period will not be refreshed, but need to jump to another window and come back before they will be refreshed.
Example: \#123
=> fix(connection): fix can not display offline message when connected

src/utils/topicMatch.ts
Shared subscriptions do not display the topic colors markers
Example: \#123
Support shared subscription marker topic colors
=> feat(topicMatch): support shared subscription marker topic colors

src/views/about/index.vue
modify utm_medium & utm_campaign
Example: \#123
=> chore(about): modify utm_medium & utm_campaign

cli/README-CN.md, cli/README.md
=> docs(readme): update cli readme

cli/README-CN.md, cli/README.md, web/README-CN.md, web/README.md
=> docs(readme): update web readme

README-CN.md, README.md, cli/README-CN.md, cli/README.md, web/README-CN.md, web/README.md
=> docs(readme): update readme

src/views/connections/ConnectionInfo.vue, web/package.json, web/src/assets/scss/element/element-reset.scss, web/src/assets/scss/theme/dark.scss, web/src/assets/scss/theme/light.scss, web/src/assets/scss/theme/night.scss, web/src/components/MsgLeftItem.vue, web/src/components/MsgPublish.vue, web/src/components/MsgRightItem.vue, web/src/components/MsgTypeTabs.vue, web/src/components/SubscriptionsList.vue, web/src/types/global.d.ts, web/src/views/connections/ConnectionInfo.vue, web/src/views/connections/ConnectionsDetail.vue, web/src/views/connections/ConnectionsList.vue, web/src/views/connections/index.vue
Example: \#123
Update MQTT X Web styles to sync with MQTT X Desktop styles.
=> style(web): synchronize styles

src/lang/connections.ts, src/views/connections/ConnectionsDetail.vue
Example: \#123
Add publish topic validation.
=> feat(desktop): add publish topic validation

cli/README-CN.md, cli/README.md, cli/src/index.ts, cli/src/lib/sub.ts
Example: \#123
```shell
mqttx sub -t 'mqttx' -h '34.219.25.208' -p 1883 -q 1 --no_local -rh 2 -rap
```
=> feat(cli/sub): add mqtt5 sub options

src/utils/mqttUtils.ts
Not able to receive Publish messages from broker with Topic Alias set after connecting with non-zero Topic Alias Maximum in CONNECT.
1036
Temp workaround until bug is fixed in upstream MQTT.js, or their API is changes with new future version.
- [ x] No
https://github.com/mqttjs/MQTT.js/pull/1519
https://github.com/emqx/MQTTX/issues/1036
=> fix(Topic Aliases): not able to receive messages with Topic Alias set

web/src/components/SubscriptionsList.vue, web/src/database/index.ts, web/src/lang/settings.ts, web/src/store/getter.ts, web/src/store/modules/app.ts, web/src/types/global.d.ts, web/src/views/settings/index.vue
=> feat(web): support multi topics subscribe

web/src/database/index.ts, web/src/lang/settings.ts, web/src/store/getter.ts, web/src/store/modules/app.ts, web/src/types/global.d.ts, web/src/views/connections/ConnectionsDetail.vue, web/src/views/settings/index.vue
=> feat(web): support autoscroll setting

cli/README-CN.md, cli/README.md, cli/src/index.ts, cli/src/utils/parse.ts
=> fix(cli): remove ws, wss of protocol option

src/background.ts, src/database/useConnection.ts
No Issue
Equal to previous
Fix the function `ConnectionDestroy` spell error and rename it as `ConnectionDestroy`
No
=> style(spell): fix function spell error

.github/workflows/build_cli.yaml
=> feat(cli): add publish npm package action

src/views/connections/ConnectionsDetail.vue
After receiving the `Retain Message` and disconnecting, the `Retain Message` disappeared. It was found that the stored retain message was not associated with the `connection id`, but normal messages sent and received can be associated with the `connection id`, so this is a temporary solution, adding setTimeout function.
Example: \#123
=> fix(connection): fix console error of timed message [temp]

src/utils/convertPayload.ts, src/views/connections/ConnectionsDetail.vue
=> feat(connection): support hex format

.github/PULL_REQUEST_TEMPLATE.md, README-CN.md, README-JP.md, README.md, cli/README-CN.md, cli/README.md, docs/manual-cn.md, docs/manual-jp.md, docs/manual.md, web/README-CN.md, web/README.md
=> docs(branch): modify github links

docs/script-example/dynamicSwitch.js, src/views/script/index.vue
=> docs(script): add dynamic switch command to example

cli/src/index.ts, cli/src/lib/conn.ts, cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/types/global.d.ts, cli/src/utils/parse.ts
Example: \#123
Support auto reconnect.
**conn**
**pub**
Valid only when sending multiple messages.
**sub**
=> feat(cli): support auto reconnect

cli/src/lib/conn.ts, cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/utils/signale.ts
=> fix(cli): fix the connection count bug

cli/src/index.ts
=> fix(cli): remove default value for option description

src/database/database.config.ts, src/database/migration/1668672504891-modifyDefaultValueOfAutoScrollInterval.ts, src/database/models/SettingEntity.ts, src/store/modules/app.ts, src/views/settings/index.vue, web/src/database/index.ts, web/src/views/settings/index.vue
=> chore(desktop & web): modify default value of auto scroll interval

cli/src/lib/conn.ts, cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/utils/signale.ts
=> feat(cli): improve start log

cli/src/lib/sub.ts, cli/src/types/global.d.ts, cli/src/utils/parse.ts
=> fix(cli): allow multiple occurrences of the same name in user properties

src/database/services/ConnectionService.ts, src/store/modules/app.ts, src/types/global.d.ts, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionsDetail.vue, src/views/connections/ConnectionsList.vue, src/views/connections/index.vue
=> improve(desktop): remove some useless data from vuex

src/database/services/ConnectionService.ts, src/database/services/WillService.ts, src/database/useServices.ts, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionInfo.vue, src/views/connections/ConnectionsList.vue, src/views/connections/index.vue
=> improve(desktop): improve update connection logic

src/components/MessageList.vue, src/components/MsgTip.vue, src/lang/common.ts, src/views/connections/ConnectionsDetail.vue
=> improve(desktop): improve code for new message notifications

src/components/SubscriptionsList.vue
=> fix(desktop): fix bytes statistics

src/components/ExportData.vue, src/components/ImportData.vue, src/database/services/ConnectionService.ts
=> fix(desktop): fix data error when exporting csv file

package.json, src/components/ExportData.vue, src/components/ImportData.vue, src/types/shims-vue.d.ts, src/utils/exportData.ts, yarn.lock
=> fix(desktop): fix the bug of import xml or csv file

src/assets/scss/theme/dark.scss, src/components/ImportData.vue, src/utils/element.ts, src/views/connections/ConnectionsDetail.vue
=> improve(desktop): add loading animation for import data

src/components/ImportData.vue, src/lang/connections.ts, src/utils/element.ts
=> feat(desktop): add import data tip

cli/src/index.ts, cli/src/lib/sub.ts, cli/src/types/global.d.ts, cli/src/utils/parse.ts
https://www.emqx.io/forum/t/can-mqttx-sub-write-to-stdout-the-payload-without-decorations/139
=> feat(cli): support output mode for the sub command

cli/README-CN.md, cli/README.md, cli/src/index.ts
=> docs(cli): add output mode option

src/components/ExportData.vue
=> improve(desktop): add loading animation for export data

.github/workflows/cr.yaml
=> ci: add code review bot

src/utils/mqttUtils.ts, src/views/connections/ConnectionsDetail.vue
Example: \#123
Update and fix client authentication for MQTT 3.1.1 and 5.0
This PR aims to address the differences in handling usernames and passwords between MQTT protocol versions 3.1.1 and 5.0 and ensure the correct usage of EMQX's ClientID authentication. The changes will improve the compatibility and user experience when connecting to different MQTT brokers and protocol versions.
=> fix(mqtt):  handle missing username with password

src/components/KeyValueEditor.vue
When the checkedList is empty, the KeyValueEditor component does not trigger the change event with null as the value.
Example: #1246 
With this PR, the KeyValueEditor component will now trigger the change event with null as the value when the checkedList is empty.
=> fix(keyvalue): trigger change event with null

src/components/MsgPublish.vue
Example: \#123
This Pull Request resolves an issue where users must click the "Save" button twice to save meta data successfully. The changes in this PR streamline the process, allowing users to save the metadata with a single click and improve code readability and maintainability.
1. Refactored and introduced isValidProp() function for better code reusability.
2. Updated getHasMqtt5PropState() function to use isValidProp() and Object.values() for better performance and readability.
3. Modified saveMeta() function to update hasMqtt5Prop after calling updatePushProp().
Are there any specific …
=> fix(meta): fix meta data saving issue requiring two clicks

cli/README-CN.md, cli/README.md, cli/src/index.ts, cli/src/lib/conn.ts, cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/types/global.d.ts
=> fix(cli): fix typo

package.json, yarn.lock
=> Revert "chore(deps): bump sqlite3 from 5.0.4 to 5.1.5"

cli/src/utils/parse.ts, cli/src/utils/simulate.ts
=> fix(cli): add js file validation

cli/package.json, cli/src/index.ts, cli/src/lib/ls.ts, cli/src/types/global.d.ts, cli/yarn.lock
Currently, MQTTX CLI does not allow users to list all the available built-in scenarios. This creates a usability issue since users may not be aware of all the available scenarios they can use.
Example: \#123
This PR adds a new ls command to the MQTTX CLI. When used with the --scenarios option, this command will list all the available built-in scenarios and their descriptions. This will make it easier for users to discover and use the built-in scenarios.
=> feat(cli): add ls command

cli/README-CN.md, cli/README.md
=> docs(cli): update ls command

cli/Dockerfile, web/Dockerfile
Example: \#123
Use the alpine image, a lighter base image to build the MQTTX CLI Docker, and be able to reduce the size by 600MB.
In the future we could consider putting the pkg compiled binary package into an alpine image that does not contain the nodejs runtime.
The image would then be only 60MB in size.
The reason for not implementing this now is that it requires a more complex build step
=> chore(dockerfile): use alpine images to reduce the size of Docker images

cli/README-CN.md, cli/README.md, cli/src/scenarios/smart_home.ts, scripts-example/IoT-data-scenarios/smart_home.js
Example: \#123
```shell
mqttx simulate -sc smart_home
```
=> feat(cli): add smart home scenario

cli/Dockerfile
Example: \#123
This Dockerfile incorporates several common practices to optimize the image size and reduce the final image's overall size:
1. Multi-stage builds: It uses multiple build stages (build and runtime) to separate the build process from the final runtime image. The build stage is responsible for compiling and building the application, while only necessary files are copied from it to the runtime stage. This helps to avoid including build tools and dependencies in the final image, resulting in a smaller image size.
2. Lightweight base image: The Dockerfile selects `node:16-alpine` as …
=> chore(cli): reduce the docker image size

src/views/help/index.vue, web/src/views/help/index.vue
=> feat(help): add mqtt ebook download link

cli/package.json, cli/src/index.ts, cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/types/global.d.ts, cli/src/utils/parse.ts, cli/src/utils/protobuf.ts, cli/yarn.lock
#555 
support messages in protobuf format
```
.option('-Pp, --protobuf-path <PATH>', 'the .proto file that defines the message format of protobuf')
.option('-Pmn, --protobuf-message-name <NAME>', 'the name of the protobuf message type')  
```
=> feat(cli):support protobuf format

cli/src/index.ts, cli/src/lib/pub.ts, cli/src/types/global.d.ts, cli/src/utils/convertPayload.ts, cli/src/utils/parse.ts, cli/src/utils/protobuf.ts
only support json format type
support hex, base64, json format type
```
.option(
'-Pf, --protobuf-format <TYPE>',
'the format type of message body, support base64, json, hex',
parseFormat,
)
```
=> feat(cli):support more format type to publish protobuf

cli/src/index.ts, cli/src/lib/pub.ts, cli/src/types/global.d.ts, cli/src/utils/parse.ts, cli/src/utils/protobuf.ts, cli/src/utils/protobufErrors.ts
optimized parameter checks and error handling
=> fix(cli):optimized parameter checks and error handling

cli/src/index.ts, cli/src/lib/pub.ts, cli/src/types/global.d.ts, cli/src/utils/parse.ts, cli/src/utils/protobuf.ts, cli/src/utils/protobufErrors.ts
[#1328 ](https://github.com/emqx/MQTTX/issues/1328)
feat(cli):support input formatted messages to publish
mqttx pub
```
.option('-f, --format <TYPE>', 'the format type of the input message, support base64, json, hex', parseFormat)
```
=> feat(cli):support input formatted messages to publish

cli/README-CN.md, cli/README.md, cli/src/index.ts
update docs about ws and protobuf support
=> docs(cli):update docs about ws and protobuf support

cli/package.json, package.json, src/version.ts, web/package.json
=> chore(pkg): upgrade version 1.9.4

src/assets/scss/theme/dark.scss, src/assets/scss/theme/light.scss, src/assets/scss/theme/night.scss, src/components/MsgLeftItem.vue, src/components/MsgRightItem.vue, src/database/database.config.ts, src/database/migration/1688042450818-supportSchemas.ts, src/database/migration/1688449795669-saveScriptName.ts, src/database/models/MessageEntity.ts, src/database/models/ScriptEntity.ts, src/lang/connections.ts, src/types/global.d.ts, src/utils/element.ts, src/views/connections/ConnectionsDetail.vue
add script tags in messageList
=> feat(connections):add script tags

package.json, src/assets/scss/theme/custom/protobuf-editor-dark.json, src/assets/scss/theme/custom/protobuf-editor-night.json, src/assets/scss/theme/custom/protobuf-editor.json, src/components/Editor.vue, src/main/updateChecker.ts, src/views/script/index.vue, yarn.lock
1. support dark mode
2. fix update bugs
=> fix(desktop):fix bugs about schema

cli/package.json, cli/yarn.lock
=> chore(cli):add js-yaml types

src/views/connections/ConnectionsDetail.vue
text processing errors automatically remove escaped characters
[#1355 ](https://github.com/emqx/MQTTX/issues/1355)
remove this operation
=> fix(connections):fix text processing error

.github/workflows/build_packages.yaml
=> chore(ci): add node version

src/views/connections/ConnectionsDetail.vue, src/views/update/index.vue
window.onresize  events can bind only one event at a time, causing overrides
（multiple components use window.onresize events）
#1354 
use event listeners instead of onsize events
refer link: https://www.cnblogs.com/wangweizhang/p/12874679.html
=> fix(connections-detail):use event listeners instead of onsize events

src/assets/scss/base.scss, src/components/SubscriptionsList.vue
Different system scrollbar size is different, occupy different space, affect the display effect. (e.g. Win, Mac)
#1319 
1. Set overflow to overlay and scrollbar to take up no space.  `overflow: overlay;`
refer link:[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow)
2. Uniform scrollbar styles.
=> style(subscriptions-list):modify scrollbar style

src/components/KeyValueEditor.vue, src/components/MsgLeftItem.vue, src/components/MsgRightItem.vue
the message display truncates long user properties, does not expand as space is available.
#1357 
modify el-input styles
=> style(key-value-editor):modify el-input styles

src/components/KeyValueEditor.vue, src/components/SubscriptionsList.vue, src/views/connections/ConnectionsList.vue
=> style(connections):fix some styles

src/components/MsgLeftItem.vue
=> style(msg-left-item):modify topic color bar

babel.config.js, src/assets/scss/base.scss, src/assets/scss/theme/custom/prism-one-dark.scss, src/assets/scss/theme/custom/prism-one-light.scss, src/components/MsgLeftItem.vue
=> feat(msg): change the highlight code theme

src/background.ts, src/components/MsgLeftItem.vue, src/database/database.config.ts, src/database/migration/1691071794840-jsonHighlight.ts, src/database/models/SettingEntity.ts, src/lang/settings.ts, src/store/getter.ts, src/store/modules/app.ts, src/types/global.d.ts, src/views/settings/index.vue
=> feat(settings): add enabled json highlight setting

cli/README.md, cli/src/index.ts, cli/src/lib/pub.ts, cli/src/types/global.d.ts, cli/src/utils/parse.ts, web/src/types/global.d.ts, web/src/utils/mqttUtils.ts, web/src/views/connections/ConnectionForm.vue
#916 
https://github.com/mqttjs/MQTT.js/pull/1683
=> SSL ALPN protocol support (CLI & Web)

src/components/ClearUpHistoryData.vue, src/database/services/MessageService.ts, src/lang/settings.ts
=> feat(settings): clear history data include all messages

src/components/MsgPublish.vue, src/views/connections/ConnectionsDetail.vue
If you have any questions, you can refer to the [Contributing Guide](https://github.com/emqx/MQTTX/blob/main/.github/CONTRIBUTING.md).
In the current version, it's not possible to send an empty message to clear retained messages.
#1407
Now, it's possible to send empty messages correctly. For such messages, no scripts will be utilized for processing.
Fixed the issue of being unable to send empty messages.
=> fix(msg): fix can not publish clear retained message

cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/utils/convertPayload.ts, cli/src/utils/protobuf.ts
```shell
mqttx pub -t testtopic/protobuf -h 127.0.0.1 -m 'A00340168F4' --format hex
```
https://askemq.com/t/topic/5820
=> fix(cli): fix pub the wrong base64 formart message

src/components/MsgLeftItem.vue, src/components/MsgPublish.vue, src/components/MsgRightItem.vue
The MQTT5 properties are not fully displayed in the message box. For example, the payload format indicator is not displayed.
N/A
The MQTT5 properties will be fully displayed in the message box.
=> fix(msg): incomplete display mqtt5 properties in message box

web/src/views/connections/ConnectionsDetail.vue
wrong type conversion of received json messages
#1418 
=> fix(web):fix type conversion of received json messages

src/assets/scss/theme/custom/prism-one-light.scss
Build throws warnings.
> DEPRECATION WARNING: $saturation: Passing a number without unit % (0) is deprecated.
none
No warning.
none
none
=> fix(theme): add unit to avoid deprecation warning

.github/CONTRIBUTING.md, .github/CONTRIBUTING_CN.md
Old branch name `master` used.
none
New branch name is `main`.
none
none
=> fix(docs): branch name changed to `main`

cli/package.json, package.json, web/package.json
No warning if installed on old outdated nodejs.
none
Not installable on old outdated nodejs without extra ignore flag.
Removes nodejs <16.
none
none
=> feat(deps): add engines

web/package.json, web/yarn.lock
`axios` is dependency but not used.
none
Remove unused dependency.
none
none
=> chore(deps): remove unused `axios`

web/src/utils/mqttUtils.ts
When using topic alias maximum during connect, it will cause an error when receiving messages.
#1398 
fix topic-alias-maximum bug
=> fix(web):fix topic-alias-maximum error in connect

cli/src/lib/pub.ts, cli/src/utils/parse.ts
1. When using --topic-alias-maximum during sub and connect, it will cause an error when receiving messages.
It's normal to use --topic-alias-maximum when pub.
2. set a topic alias, and send multiple messages with the --multiline option, each message will contain both the topic and the topic alias.
#1398 
1. fix topic-alias-maximum bug
2. only send once topic when multiline send and topic-alias is exist
=> fix(cli):fix topic-alias-maximum error in cli connect

packages/core/package.json, packages/core/src/utils/__test__/getMessageId.test.ts, packages/core/tsconfig.json, packages/core/vitest.config.ts, packages/ui/src/components/__test__/EmptyView.spec.ts, packages/ui/src/composables/__test__/useLinks.test.ts, packages/ui/src/i18n/__test__/i18n.test.ts, packages/ui/src/router/__test__/router.test.ts, pnpm-lock.yaml
=> feat(packages): add unit tests to core and ui

.github/workflows/build_cli.yaml, .github/workflows/build_desktop.yaml, apps/cli/package.json
=> chore(ci): modify the build cli ci

.github/workflows/build_desktop.yaml, apps/desktop/README.md, apps/desktop/electron-builder.yml
=> Update Linux build CI

apps/desktop/README.md
=> docs(desktop): update readme

packages/ui/src/i18n/update.ts
Currently, in the MQTTX installer for version v1.9.6, there's a typo in the final dialog button. The button text reads "Install and Relunch" instead of the intended "Install and Relaunch". This issue is reported in [#1500](https://github.com/emqx/MQTTX/issues/1500).
#1500
This PR corrects the typo in the installer dialog. The button now correctly states "Install and Relaunch". This change enhances the professionalism of the interface and eliminates any confusion caused by the typo.
No specific instructions. The change is a simple text update and does not affect any functionality or other aspects of the MQTTX application.
The fix is straightforward and was tested to ensure that no other parts of the application are impacted. This change will be included in the upcoming v1.9.7 release of …
=> fix(ui): fix update typo

src/lang/update.ts
Currently, in the MQTTX installer for version v1.9.6, there's a typo in the final dialog button. The button text reads "Install and Relunch" instead of the intended "Install and Relaunch".
#1500
This PR corrects the typo in the installer dialog. The button now correctly states "Install and Relaunch". This change enhances the professionalism of the interface and eliminates any confusion caused by the typo.
No specific instructions. The change is a simple text update and does not affect any functionality or other aspects of the MQTTX application.
The fix is straightforward and was tested to ensure that no other parts of the application are impacted. This change will be included in the upcoming v1.9.7 release of MQTTX.
=> fix(update): fix typo

src/components/Copilot.vue, src/database/database.config.ts, src/database/models/CopilotEntity.ts, src/database/services/CopilotService.ts, src/database/services/SettingService.ts, src/database/useServices.ts, src/types/global.d.ts, src/utils/idGenerator.ts, src/views/connections/ConnectionsDetail.vue
=> feat(copilot): add copilot database table

src/database/database.config.ts, src/database/migration/1701936842016-aiTables.ts
=> refactor(database): add copilot table migrate script

cli/src/utils/jsonUtils.ts, src/utils/jsonUtils.ts, web/src/utils/jsonUtils.ts
The functions JSONBigInt.parse() and JSONBigNumber.parse() generate an error when encountering an invalid JSON string, but do not properly throw it.
=> fix:throw an error for invaild json string

cli/package.json, package.json, src/background.ts, src/database/database.config.ts, src/database/migration/1703659148195-enableCopilot.ts, src/database/models/SettingEntity.ts, src/lang/settings.ts, src/store/getter.ts, src/store/modules/app.ts, src/types/global.d.ts, src/version.ts, src/views/connections/ConnectionsDetail.vue, src/views/settings/index.vue, web/package.json
Example: #1534 
Users can deactivate the current settings When they do not want to pass test data through the OpenAI API. If the OpenAI API Key is not set, no data will be sent to OpenAI. To ensure peace of mind for our users, we provide a toggleable configuration.
=> feat(settings): add enable copilot switch

cli/README.md
=> docs(cli): update cli readme

src/lang/connections.ts, src/views/connections/ConnectionsDetail.vue
=> feat(desktop): connection support disconnect and offline event

cli/src/lib/conn.ts, cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/utils/signale.ts
=> feat(cli): add disconnect event

src/App.vue, src/components/ClearUpHistoryData.vue, src/components/SubscriptionsList.vue, src/views/connections/ConnectionsDetail.vue, src/views/connections/ConnectionsList.vue
Example: \#123
Are there any specific instructions or things that should be known before review?
=> refactor(desktop): improve log message clarity and consistency

src/background.ts, src/database/database.config.ts, src/database/migration/1704941582350-logLevel.ts, src/database/models/SettingEntity.ts, src/lang/log.ts, src/plugins/logPlugin/index.ts, src/plugins/logPlugin/logConfig.json, src/store/getter.ts, src/store/modules/app.ts, src/types/global.d.ts, src/types/logPlugins.d.ts, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionsDetail.vue, src/views/log/index.vue, src/views/settings/index.vue
=> feat(settings): add log level field

cli/README.md, web/README.md
The specific installation methods and parameter list are not displayed in the CLI's README. Please take a look at the official website or documentation for more information.
=> docs(readme): simplify cli readme

src/views/connections/ConnectionsDetail.vue
Reconnection will happen indefinitely.
Example: #1532 #1552 
Reconnection will only be maintained when on the current connecting page. If you leave the current connecting page, reconnection should be stopped immediately. This can solve many repetitive and meaningless reconnection prompts.
=> fix(connection): the reconnect can only works on current page

package.json, src/components/MsgLeftItem.vue, src/components/MsgPublish.vue, src/database/database.config.ts, src/database/migration/1705478422620-updatePayloadTypeToVarchar.ts, src/database/models/HistoryMessagePayloadEntity.ts, src/types/global.d.ts, src/views/connections/ConnectionsDetail.vue
Add a new cbor type, the error in the console.
Example: #1547 
Manually update the migration script to change the payload type to a more flexible and extensible string type to facilitate future expansion. It is very troublesome to update using a simple enum due to the limitation of typeorm.
=> refactor(msg): payload type table migration and update

src/assets/scss/connections.scss, src/components/EmptyPage.vue, src/components/MsgPublish.vue, src/components/SubscriptionsList.vue, src/store/getter.ts, src/store/modules/app.ts, src/types/global.d.ts, src/views/Home.vue, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionsDetail.vue, src/views/connections/ConnectionsList.vue, src/views/connections/index.vue, yarn.lock
Example: #1511 #883 
Remove the show sub-list state first and conn-list support.
=> feat(desktop): connection list hide support

src/components/EmptyPage.vue, src/components/SubscriptionsList.vue, src/utils/styles.ts, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionsDetail.vue
This is not a good design for UI layout, but it's hard to change for 1.9.x; we can only manage these space values in one file.
=> refactor(desktop): extracted hard-coded style values into enums

cli/src/index.ts, cli/src/lib/pub.ts, cli/src/types/global.d.ts
The `bench pub` command cannot limit the total number of messages sent.
\#1360
- The message will not be sent until all connections are established.
- Support limiting the total number of messages.
=> feat(cli): add message limit option to bench pub command

cli/src/index.ts, cli/src/lib/sub.ts
**Updated the `--verbose` mode to show mqtt packet**
=> refactor(cli): display from topic & qos in sub

cli/src/index.ts
The "simulate" command cannot limit the total number of messages sent.
\#1597
=> feat(cli): add message limit option to simulate command

src/views/connections/ConnectionsDetail.vue
Restarting \ switching tools will change the default value of plaintext, resulting in other encoded messages will be garbled.
\#903
Remember the encoding/decoding type selected by the user.
=> feat(desktop): remember the selected encode/decode type

src/lang/common.ts, src/views/connections/ConnectionForm.vue, src/views/connections/index.vue, web/src/lang/common.ts, web/src/views/connections/ConnectionForm.vue, web/src/views/connections/index.vue
When you want to make a new connection and fill in some (but not necessarly all) fields you can't temporailty save it and complement it later on. You can only choose Connect which is not always what you want. The same goes for editing connections.
#735
When creating or editing connection information, the current information can be saved. Instead of clicking the `Connect` button to establish a connection.
=> feat(desktop): add save button for new & edit connection

cli/src/lib/conn.ts, cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/types/global.d.ts, cli/src/utils/mqttErrorReason.ts, cli/src/utils/signale.ts, src/lang/connections.ts, src/utils/mqttErrorReason.ts, src/views/connections/ConnectionsDetail.vue, web/src/lang/connections.ts, web/src/views/connections/ConnectionsDetail.vue
#1329 
This feature is only supported when using MQTT 5.0
desktop & web:
cli:
```bash
[2024/3/30] [21:42:09] › ⚠  The Broker has actively disconnected, Reason: Administrative action (Code: 152)
```
```bash
[2024/3/30] [21:52:40] › ⚠  Client ID: test_4, The Broker has actively disconnected, Reason: Administrative action (Code: 152)
[2024/3/30] [21:52:40] › ⚠  Client ID: test_5, The Broker has actively disconnected, Reason: Administrative action (Code: …
```
=> feat(desktop): display the reason and code for the disconnection

.github/workflows/deploy_web.yaml, web/.env, web/.env.docker, web/package.json, web/src/utils/mqttUtils.ts, web/vue.config.js
Currently, `BASE_URL` is set in `vue.config.js`, and users may not be able to quickly find out how to modify `BASE_URL`.
#1575
Support to modify configuration by exposing env files.
Distinguishing between the build environment and the docker environment.
Remove related useless step from ci.
[Modes and Environment Variables | Vue CLI](https://cli.vuejs.org/guide/mode-and-env.html)
Later, I will update readme to improve user-friendliness.
=> feat(web): add env file to support configuration of BASE_URL

web/README-CN.md, web/README.md
#1575 
Add docker local deployment guide. 
Support for PR#1619
=> docs(web-readme): add docker local deployment guide

src/background.ts, src/components/DatabaseError.vue, src/store/getter.ts, src/store/modules/app.ts, src/types/global.d.ts, src/utils/rebuildDatabase.ts, src/views/Home.vue
The current behavior is that the application displays a blank screen when the database file is corrupted, preventing users from interacting with the application.
#1370
The new behavior is that upon detecting a database corruption, the application will redirect the user to an error page where they can initiate a database reset. This resolves the white screen issue and allows the user to restore the application to a working state.
If you wish to conduct testing, you can do so by altering the fields within the `MQTTX.db` file in the application data to make them non-conforming to the schema.
The UI and UX for the error page and database reset feature are still …
=> feat(desktop): add database reset page to fix blank screen from corrupted file

cli/src/index.ts, cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/types/global.d.ts, cli/src/utils/fileUtils.ts, cli/src/utils/parse.ts, cli/src/utils/signale.ts
The bench feature does not support reading messages from files.
This PR adds support for reading messages from files in the bench feature, allowing users to send messages from file sources.
=> feat(cil): support for reading messages from files in bench

cli/src/index.ts, cli/src/lib/sub.ts, cli/src/utils/parse.ts
The CLI incorrectly handles the `--file-write` option make subscribe error.
NONE
The CLI tool correctly handles the `--file-write` option, ensuring that received messages are properly appended to the specified file.
=> fix(cli): fix options handler of file write

cli/package.json, cli/src/index.ts, cli/src/lib/pub.ts, cli/src/types/global.d.ts, cli/src/utils/fileUtils.ts, cli/yarn.lock, src/database/services/MessageService.ts
=> feat(cli): bench pub support split file content

cli/src/index.ts, cli/src/lib/pub.ts, cli/src/types/global.d.ts, cli/src/utils/fileUtils.ts, cli/src/utils/parse.ts
=> fix(cli): fix split option bugs & set default value for split option

cli/src/index.ts
=> fix(cli): fix can not display split default value

cli/src/index.ts, cli/src/lib/sub.ts, cli/src/types/global.d.ts, cli/src/utils/fileUtils.ts
Users cannot change the delimiter for writing to a file because the default value is only the '\n.'
```plaintext
{"temp":59,"hum":86}
{"temp":71,"hum":75}
{"temp":36,"hum":40}
{"temp":53,"hum":49}
```
```shell
mqttx bench pub -c 1 -h 127.0.0.1 -t 'smart_home' --file-read ./data-split-newline.txt --split -im 1000
```
```shell
mqttx sub -h 127.0.0.1 -p 1883 -t smart_home --file-write ./delimiter-file.txt --delimiter ','
```
```plaintext
{"temp":59,"hum":86},{"temp":71,"hum":75},{"temp":36,"hum":40},{"temp":53,"hum":49},
```
=> feat(cli): add delimiter option for sub file write

web/src/components/ClearUpHistoryData.vue, web/src/lang/connections.ts, web/src/lang/settings.ts, web/src/utils/api/setting.ts, web/src/views/settings/index.vue
=> feat(web): support clearing historical data

web/src/components/ExportData.vue, web/src/lang/common.ts, web/src/lang/connections.ts, web/src/utils/api/setting.ts, web/src/views/settings/index.vue
=> feat(web): support data export

cli/Dockerfile, cli/package.json, cli/yarn.lock
=> chore(cli): upgrade the node version to 18

cli/package.json, cli/src/configs/common.ts, cli/src/configs/index.ts, cli/src/configs/init.ts, cli/src/configs/load.ts, cli/src/index.ts, cli/src/types/global.d.ts, cli/yarn.lock
=> feat(cli): support init and load config file

cli/src/lib/sub.ts
The error was caused by connection delays, which caused multiple subscription callbacks to trigger log messages simultaneously. Adding the `subscribedCount` variable and the `isLogged` flag ensures that the log message is only executed once.
=> fix(cli): fix bench sub duplicate logs

cli/src/lib/conn.ts, cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/utils/logWrapper.ts, src/views/connections/ConnectionsDetail.vue
> CLI Publish retries in the loop if disconnected by an invalid topic
Example: #1667
=> fix(cli): update wrong prompt type when error

cli/src/configs/common.ts, cli/src/configs/load.ts, cli/src/index.ts, cli/src/lib/init.ts, cli/src/types/global.d.ts
Only can set the max-reconnect-times in the CLI options
=> feat(cli): config support max reconnect times

cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/utils/logWrapper.ts
Handle individual topic subscription success and failure separately
- Refactor to use `Promise.all` for concurrent subscription handling
- Log each topic's subscription status independently
- Ensure individual topic failures do not affect others
- Explicitly define return types for subscription promises
- Improve performance by reducing redundant checks
=> fix(cli): fix sub error logic with multi topics

cli/src/lib/sub.ts, cli/src/utils/logWrapper.ts
1.	Improved Logging for Multiple Topics: Ensure log messages accurately display all subscribed topics.
2.	Independent Multi-Topic Subscription: Ensure that subscriptions to multiple topics do not interfere with each other.
3.	Effective Error Differentiation: Improve error messages to differentiate between different types of errors.
4.	Display Connection Information: Add functionality to log detailed connection information.
=> refactor(cli): improve bench sub logs

src/views/update/index.vue
=> fix(desktop): version update dialog adapt to dark mode

src/views/connections/ConnectionsDetail.vue
The current subscribers of the observer repeatedly process a message multiple times.
By using shareReplay(1), the message processing results are cached and shared, avoiding duplicate processing while ensuring all subscribers can correctly handle different messages. These changes ensure that each message is processed only once without affecting the original business logic and functionality.
=> fix(desktop): share one message event

cli/src/lib/pub.ts
When publishing a message using the `mqttx pub` command with the `format` option specified, the received data differs from the original data. This issue occurs because the data read from a file is already a `Buffer`. However, the conversion process unnecessarily converts it to a string and back to a `Buffer`, causing data corruption.
Example: #1692 #1694 
The new behavior ensures that unnecessary conversions are avoided when a message is read from a file and the `format` option is specified. The `convertPayload` function now correctly handles the `binary` format without additional transformations. This fix ensures the integrity of the data during the publishing process.
None.
The updated function now:
- Checks if `format` is specified and applies format conversion only if necessary.
- …
=> fix(cli): correct data conversion for publishing messages with format

src/components/SubscriptionsList.vue, web/src/components/SubscriptionsList.vue
=> fix(subscription): fix issue with resubscribing

cli/src/lib/sub.ts, cli/src/types/global.d.ts, cli/src/utils/logWrapper.ts
=> fix(cli): highlight sub info on sub output

src/assets/scss/element/element-reset.scss, src/components/ImportData.vue, src/components/MyDialog.vue, src/database/services/ConnectionService.ts, src/database/services/MessageService.ts, src/lang/settings.ts, src/views/connections/ConnectionsDetail.vue
Data import does not allow file path updates. You can only select files via Dialog.
Can not import extensive data included on backup file.
Example: #1696 
You can now update the file content by manually inputting a new path, not just by selecting the file via Dialog.
Support showing importing progress, allowing users to monitor the current status.
Are there any specific instructions or things that should be known before review?
=> Improve the Desktop Backup Import

.github/workflows/deploy_web.yaml
=> chore(ci): fix web client deploy job

src/background.ts, src/components/Copilot.vue, src/database/database.config.ts, src/database/migration/1716044120271-supportOpenAIAPIHost.ts, src/database/models/SettingEntity.ts, src/store/getter.ts, src/store/modules/app.ts, src/types/global.d.ts, src/views/settings/index.vue
Currently, the copilot API interface only supports OpenAI's host and model.
#1542 
The API interface of Copilot supports setting all request addresses and models that are compatible with the OpenAI API protocol.
Supporting third-party large model interfaces has two main benefits:
1. Supporting API calls for large models such as [ChatGLM](https://open.bigmodel.cn/dev/api#openai_sdk) and [DeepSeek](https://platform.deepseek.com/api-docs/) can provide cheaper and faster services, and can be deployed in regions where OpenAI cannot be directly used (such as China).
2. Companies using MQTTX can privatize their own large model services, compatible with OpenAI's …
=> feat(copilot): support custom copilot api

src/views/settings/index.vue
Users in China are unable to use the Copilot capabilities quickly.
Example: #1542 
Based on the custom API and model capabilities provided by #1660, it expands interaction and provides built-in API models and endpoints with Moonshot.
=> feat(desktop): moonshot llm api support on copilot

src/views/connections/index.vue
No one can see all the errors when loading data error.
Example: \#123
Show the error messages on the page and logs
=> fix(desktop): support show load data errors

package.json, src/background.ts, src/components/Ipc.vue, src/lang/menu.ts, src/lang/settings.ts, src/main/getMenuTemplate.ts, src/main/installCLI.ts, src/views/settings/index.vue, yarn.lock
The desktop version and the CLI version installations are relatively independent, and users need to download them separately in different scenarios.
Example: None
After downloading the desktop version, allow users to directly install MQTTX CLI with one click if needed.
=>  feat(desktop): support install mqttx cli one click

cli/src/index.ts, cli/src/types/global.d.ts, cli/src/utils/parse.ts
I apologize for the misunderstanding. Here's the PR information in English:
Currently, the MQTTX command-line tool does not allow customization of WebSocket headers when using WebSocket connections.
Example: #1722 
Added the ability to customize WebSocket headers through the `-wh` parameter in the command line. For example:
```shell
mqttx sub -t test -wh "hello: test" -wh "auth: token" -l ws -p 8083
```
When reviewing this PR, please note the following:
1. This feature is implemented only in the command-line tool running in a Node.js environment.
2. Test scenarios with multiple `-wh` parameters to ensure multiple headers are correctly added.
3. Verify that …
=> feat(cli): custom ws headers support

cli/package.json, cli/src/index.ts, cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/types/global.d.ts, cli/src/utils/avro.ts, cli/src/utils/parse.ts, cli/src/utils/protobuf.ts, cli/yarn.lock
Support only protobuf as schema-based encoding. (cli)
None
Support avro encoding now. (cli)
I wonder what tests should be written to test the function and stability.
=> feat(cli): add avro support

cli/src/state/index.ts, cli/src/utils/logWrapper.ts
=> chore(cli): optimize configuration loading logic

src/database/services/MessageService.ts
The topic matching with '#' has an issue. For example, 'foo/#' can incorrectly match 'foobar/#' messages.
Example: #1734
Fix this issue.
=> fix(desktop): improve MQTT wildcard topic matching for '#'

src/database/services/MessageService.ts
=> fix(desktop): correct handling of '#' wildcard in topic filtering

src/background.ts, src/database/database.config.ts, src/database/migration/1724839386732-ignoreQoS0Message.ts, src/database/models/SettingEntity.ts, src/lang/settings.ts, src/store/getter.ts, src/store/modules/app.ts, src/types/global.d.ts, src/utils/mqttUtils.ts, src/views/connections/ConnectionsDetail.vue, src/views/settings/index.vue
All messages will be stored
Example: None
According to the MQTT protocol specification, it supports ignoring QoS messages and not storing them locally. When enabled, this can optimize performance for receiving and publishing large volumes of messages
=> feat(desktop): support enable ignore qos 0 messages

src/views/connections/ConnectionForm.vue
Currently, for MQTT v5 with a clean start set to false, the Session Expiry Interval is set to never expire by default. This can lead to persistent connections that may unnecessarily consume resources, especially in Serverless environments where it can affect billing.
Example: #123
This PR proposes to change the default Session Expiry Interval from never expire to 7200 seconds (2 hours, keep with EMQX default config) when using MQTT v5 with clean start set to false. This change aims to balance connection persistence with resource management.
Proposed changes:
- Modify the default Session Expiry Interval to 7200 seconds for MQTT v5 when clean start is false. …
=> refactor(deskop): session expriy default to 7200

.github/workflows/units_test_cli.yaml, cli/.gitignore, cli/jest.config.js, cli/package.json, cli/src/__tests__/utils/binaryFormats.test.ts, cli/src/__tests__/utils/delay.test.ts, cli/src/__tests__/utils/jsonUtils.test.ts, cli/src/utils/binaryFormats.ts, cli/tsconfig.json, cli/yarn.lock
No any testing framework support.
Example: \#123
=> feat(cli): test support

src/utils/mqttErrorReason.ts, src/utils/mqttUtils.ts, tests/unit/components/ResizeHeight.spec.ts, tests/unit/utils/SystemTopicUtils.spec.ts, tests/unit/utils/convertPayload.spec.ts, tests/unit/utils/copilot.spec.ts, tests/unit/utils/delay.spec.ts, tests/unit/utils/exportData.spec.ts, tests/unit/utils/gaCustomLinks.spec.ts, tests/unit/utils/getContextmenuPosition.spec.ts, tests/unit/utils/getFiles.spec.ts, tests/unit/utils/handleString.spec.ts, tests/unit/utils/idGenerator.spec.ts, tests/unit/utils/jsonUtils.spec.ts, tests/unit/utils/matchMultipleSearch.spec.ts, tests/unit/utils/mqttErrorReason.spec.ts, tests/unit/utils/protobuf.spec.ts, tests/unit/utils/protobufErrors.spec.ts, tests/unit/utils/time.spec.ts
=> test(desktop): add more utils test cases

cli/src/__tests__/utils/binaryFormats.test.ts, cli/src/__tests__/utils/delay.test.ts, cli/src/__tests__/utils/jsonUtils.test.ts, cli/src/__tests__/utils/mqttErrorReason.test.ts, cli/src/__tests__/utils/parse.test.ts, cli/src/__tests__/utils/protobufErrors.test.ts, cli/src/__tests__/utils/simulate.test.ts
=> test(cli): add more utils test cases

cli/src/__tests__/utils/avro.test.ts, cli/src/__tests__/utils/mockData/invalidSchema.avsc, cli/src/__tests__/utils/mockData/mockAvroSchema.avsc, cli/src/lib/sub.ts, cli/src/utils/avro.ts
=> test(cli): add avro util test cases

tsconfig.json
modern lsp like volar would complain about variables used in template without this option.
**error in line 23 is already addressed in another pr.**
Haven't tried it on VSCode, but since I'm using the same lsp as VSCode popular plugin uses, it should behave the same.
=> chore(config): add experimental option in tsconfig to fit modern lsp

package.json, src/components/ImportScript.vue, src/components/UseScript.vue, src/database/services/ScriptService.ts, src/lang/script.ts, src/types/global.d.ts, src/utils/avro.ts, src/utils/protobuf.ts, src/utils/schemaUtils.ts, src/utils/scriptTest.ts, src/views/connections/ConnectionsDetail.vue, src/views/script/index.vue, yarn.lock
=> feat(desktop): add avro support

src/utils/avro.ts, tests/unit/utils/avro.spec.ts
=> test(desktop): add avro util test cases

src/components/ImportScript.vue, src/types/global.d.ts, src/views/script/index.vue
=> improve(desktop): improve experience with avro

src/database/database.config.ts, src/database/migration/1727111519962-changeDefaultLLMModel.ts, src/database/models/SettingEntity.ts, src/store/modules/app.ts, src/types/global.d.ts, src/views/settings/index.vue
Example: #1763 
More GPT models, such as GPT-4o-mini and o1-preview, are supported. Among them, GPT-4o-mini is relatively more affordable. It would be great to update the default model to GPT-4o since it is undoubtedly the most useful GPT model available.
DeepSeek is one of the most affordable large language models for users in China. We have built it with support for various features to meet your diverse needs.
=> feat(copilot): change to gpt-4o to default model

src/views/script/index.vue
https://github.com/emqx/MQTTX/pull/1762#issuecomment-2363001569
Example: #1762 
- Rename `addExtension` to `checkExtension` for clarity
- Implement logic to remove incorrect extensions before adding the correct one
- Handle cases where the file already has the correct extension
- Improve code readability and maintainability
=> fix(desktop): improve file extension handling in script

src/utils/mqttUtils.ts, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionInfo.vue, web/src/views/connections/ConnectionForm.vue, web/src/views/connections/ConnectionInfo.vue
It is impossible to simulate MQTT 5 when the Client ID is empty. In this case, the MQTT Broker can automatically allocate a Client ID.
https://www.emqx.com/zh/blog/mqtt5-connect-properties
Example: https://askemq.com/t/topic/7181
Support clearing the client ID, and do not limit the client ID to a required field.
=> feat(client): allow client id empty

cli/src/utils/convertPayload.ts, package.json, src/components/MsgLeftItem.vue, src/components/MsgPublish.vue, src/types/global.d.ts, src/views/connections/ConnectionsDetail.vue, yarn.lock
Add support for Message Pack payload encoding and decoding.
=> feat(desktop): Msg pack support

src/assets/scss/atom.scss, src/assets/scss/base.scss, src/assets/scss/element/element-reset.scss, src/components/Leftbar.vue, src/components/widgets/TreeNodeInfo.vue, src/components/widgets/TreeView.vue, src/lang/connections.ts, src/lang/index.ts, src/lang/viewer.ts, src/router/routes.ts, src/types/global.d.ts, src/types/locale.d.ts, src/utils/globalEventBus.ts, src/utils/i18n.ts, src/utils/topicTree.ts, src/views/connections/ConnectionsDetail.vue, src/views/script/index.vue, src/views/viewer/TopicTree.vue, src/views/viewer/index.vue
Example: #1244 
1. Event Bus: A global event bus has been implemented to support listening to MQTT packets across all components.
2. Topic Tree View Component: A new component for visualizing MQTT topics in a tree structure has been added.
3. Tree Node Information: A new component to display detailed information about selected nodes has been introduced.
4. Real-time Topic Updates: The topic tree is updated in real-time as new MQTT packets are received.
5. Topic Filtering: Users can filter topics in the tree view using keywords.
6. Viewer Page: A new "Viewer" page has been added to the …
=> Topics Tree

src/components/widgets/TreeView.vue, src/utils/topicTree.ts, tests/unit/utils/globalEventBus.spec.ts, tests/unit/utils/topicTree.spec.ts
Example: #1244 
1. The feature allows users to expand and collapse all tree nodes.
2. Add the Topic Tree Utils test cases.
3. Add unit tests for globalEventBus
=> feat(desktop): support expand and collapse all tree nodes

src/components/widgets/TreeNodeInfo.vue, src/components/widgets/TreeView.vue, src/types/global.d.ts, src/utils/topicTree.ts, src/views/viewer/TopicTree.vue, tests/unit/utils/topicTree.spec.ts
Example: #1244 
1. Fixed duplicate key values.
2. In topic tree data, the label of a node is not absolutely unique. Add an id attribute.
=> fix(desktop): add id for tree node

src/views/connections/ConnectionsList.vue
Jumping to the new connection page or topic tree page cannot be initialized correctly if the connection has unread message statistics.
Example: \#123
Fix it.
=> fix(desktop): fix can not init unread message count issue

src/components/SubscriptionsList.vue
When hovering over topics, the tag that appears gets in the way. Long hover should have tag appear
Example: https://github.com/emqx/MQTTX/discussions/452#discussioncomment-10629550
Not immediately to show.
=> fix(desktop): delay open the topic tooltip

apps/desktop/src/renderer/src/App.vue, apps/desktop/src/renderer/src/main.ts, apps/desktop/tailwind.config.ts, apps/desktop/tsconfig.web.json, apps/web/src/App.vue, apps/web/src/main.ts, apps/web/tailwind.config.ts, package.json, packages/ui/package.json, packages/ui/src/i18n/index.ts, packages/ui/src/index.ts, packages/ui/src/styles/index.scss, packages/ui/src/vite-env.d.ts, pnpm-lock.yaml
This pull request includes several changes across multiple files to improve the structure and organization of imports, update Tailwind CSS configurations, and adjust module exports. The most important changes include refactoring imports, updating Tailwind CSS content paths, and modifying the `package.json` files for better module resolution.
Refactoring imports:
* [`apps/desktop/src/renderer/src/App.vue`](diffhunk://#diff-742de6ecc0e88763b22ebb751c98d3168acc223abb61ef63b7e9991add5914bbL2-R3): Separated imports from `@mqttx/ui` into `@mqttx/ui/i18n` and `@mqttx/ui/stores`.
* [`apps/web/src/App.vue`](diffhunk://#diff-3484783b87f953af09f16dea9b15f3b6b00410249c4acae47f327bc2e02d9e65L2-R3): Similar separation of imports from `@mqttx/ui` into `@mqttx/ui/i18n` and `@mqttx/ui/stores`.
* …
=> refactor(ui): reorganize imports

cli/package.json
@faker-js/faker is needed to run the CLI
Expected: The app should run with deps installed by `yarn install --prod`.
Current: Crashes
<details>
<summary>Log file</summary>
`--ignore-engines` is removed from the log because it should not matter.
```shell
$ yarn install && yarn build
$ node bin/index.js 
Usage: mqttx [options] [command]
...
ls [options]        List information based on the provided options.
help [command]      display help for command
$ yarn install --prod
$ node bin/index.js
node:internal/modules/cjs/loader:1148
throw err;
^
Error: Cannot find module '@faker-js/faker'
Require stack:
- /home/shogo/tmp/MQTTX/cli/dist/src/utils/simulate.js
- …
```
=> fix(cli): move @faker-js/faker to dependencies

cli/src/__tests__/utils/binaryFormats.test.ts, cli/src/utils/binaryFormats.ts
#1806 
This pull request includes updates to the `cli/src/__tests__/utils/binaryFormats.test.ts` and `cli/src/utils/binaryFormats.ts` files to expand the list of supported and unsupported binary formats for MQTT. The changes also include improvements to the test cases to handle format categories and case sensitivity.
Updates to supported and unsupported formats:
* [`cli/src/__tests__/utils/binaryFormats.test.ts`](diffhunk://#diff-c40bf988261ec53add29e28ce331d71968c737b9c791af725edc4440a5f24b5eL6-R122): Expanded the list of supported and unsupported binary formats, including new categories such as Network & Protocol formats, Database formats, IoT & Device formats, and more.
* [`cli/src/utils/binaryFormats.ts`](diffhunk://#diff-4ab77bfacbb0af0860f0a241b049d85a929173595df25fbae3ad9593c83b0f7d …
=> fix(cli): support more biarny type files

cli/src/__tests__/utils/options.test.ts, cli/src/index.ts, cli/src/lib/conn.ts, cli/src/lib/pub.ts, cli/src/lib/sub.ts, cli/src/types/global.d.ts, cli/src/utils/options.ts
\#1809
This pull request includes several changes to the `cli` package, focusing on improving the handling of options and adding pre-action hooks to commands. The most important changes include adding tests for saving and loading options, adding pre-action hooks to commands, and updating the `handleLoadOptions` function to merge options correctly.
* [`cli/src/__tests__/utils/options.test.ts`](diffhunk://#diff-48fcb7d68d45acf549d3747689e4607469c3e6fb3c677a61cadcc64a94c47d51R1-R188): Added comprehensive tests for saving and loading options for different command types, ensuring that options are correctly persisted and retrieved.
* [`cli/src/utils/options.ts`](diffhunk://#diff-899979b30b66e5771e8eafa61234393cf0dd2830a55fb23e8abc034f01edfceeR30-R41): Updated the `handleLoadOptions` function to …
=> improve(cli): enhance handleLoadOptions to accept existing options

src/components/MqttProperties.vue, src/components/MsgLeftItem.vue, src/components/MsgRightItem.vue
Example: \#123
This pull request includes changes to refactor the handling of MQTT properties in the `MsgLeftItem` and `MsgRightItem` components by creating a new `MqttProperties` component. The most important changes include the creation of the new component and the replacement of the existing property handling code in the `MsgLeftItem` and `MsgRightItem` components.
Creation of `MqttProperties` component:
* [`src/components/MqttProperties.vue`](diffhunk://#diff-e5d753006c70e802c2942a8be62eb36eb030245c3729bd6dc1d7dd392c3e6076R1-R55): Added a new component to handle the display of MQTT …
=> refactor(desktop): add mqtt properties component

cli/src/lib/conn.ts, cli/src/lib/pub.ts, cli/src/utils/exitInfo.ts, cli/src/utils/logWrapper.ts
When users successfully establish a connection using the `mqttx conn` command, the program maintains the connection state (appearing to be "hanging"). Still, there is no prompt for users to exit. This causes users to need clarification about the program's behavior.
- Users are unclear that the expected behavior of the `mqttx conn` command is to maintain the connection
- Users don't know how to exit the connection state properly
- Lack of user guidance leads to poor operational experience
Example: #1810 
```shell
❯ mqttx conn
✔ Connected
- Press Ctrl+C to disconnect and exit
```
Please …
=> feat(cli): add exit tips for conn

cli/src/index.ts, cli/src/lib/pub.ts, cli/src/types/global.d.ts
To read messages from stdin line by line, users need to use two separate options: `-s` and `-M`. This combination is not intuitive and requires users to remember to use both options together.
Example of current usage:
```bash
mqttx pub -t "topic" -s -M
```
Added a new convenient option `-lm, --line-mode` that combines the functionality of `-s` and `-M`. This makes the command more intuitive and easier to use.
New usage:
```bash
❯ mqttx pub -t test -lm
✔ Connected, input and press Enter to publish
- Press Ctrl+C to disconnect and exit
test
```
The old way (`-s -M`) still works for backward compatibility, but the new option provides a more straightforward approach.
1. The new `-lm` option is equivalent to using `-s -M` together
2. Existing code using `-s -M` will continue to work as before
=> feat(cli): line mode option support

cli/src/lib/pub.ts
Currently, when using the pipe mode with `-s -M` options in MQTTX CLI, there are several issues:
1. The command requires using two separate options (`-s -M`) for line-by-line input
2. The log output is too verbose, showing a message for each published line
3. The pipeline mode detection is not indicated
4. The code structure for handling stdin is not optimized
Current behavior:
```bash
❯ cat message.txt | mqttx pub -t test -s -M
✔ Connected, press Enter to publish, press Ctrl+C to exit
✖ Connection closed
```
N/A
1. Added a new convenient option, `-lm,` that combines `-s -M` functionality
2. Optimized log output to show a summary instead of individual messages
3. Improved code structure for better maintainability
New behavior:
```bash
cat message.txt | mqttx pub -t test -s -M
✔ Connected …
```
=> fix(cli): support pub multiple lines on pipeline

apps/desktop/electron.vite.config.ts, apps/web/vite.config.ts, packages/types/base.ts, packages/ui/src/components/HelpView.vue, packages/ui/src/components/common/LeftMenu.vue, packages/ui/src/composables/__test__/useLinks.test.ts, packages/ui/src/composables/useLinks.ts, scripts/gen-version.js
This pull request includes several changes to handle the application version dynamically and improve the localization of links based on the user's locale. The most important changes include importing the version from `package.json`, defining a global `__APP_VERSION__` variable, and updating the `useLinks` composable to provide localized links.
Handling application version dynamically:
* [`apps/desktop/electron.vite.config.ts`](diffhunk://#diff-10a3bbe3228b3f2afec6048e8a29ec7d9cbf0bd8e70c93d8c0505b88fd237263R12-R13): Imported the `version` from `package.json` and defined the `__APP_VERSION__` variable in the Vite configuration. [[1]](diffhunk://#diff-10a3bbe3228b3f2afec6048e8a29ec7d9cbf0bd8e70c93d8c0505b88fd237263R12-R13) [[2]](diffhunk://#diff-10a3bbe3228b3f2afec6048e8a29ec7d9cbf0bd8e70c93 …
=> feat(links): integrate app version and update link management

src/assets/scss/element/element-reset.scss, src/components/ConnectionSelect.vue, web/src/assets/scss/element/element-reset.scss
**Blod font-weight** is too heavy
Maked the font style softer.
=> style(desktop): improve select dropdown item style

src/views/connections/ConnectionsDetail.vue
This function requirement comes from the community. Users who are used to hiding the left list need to expand the connection list to switch to the current connection, which is inconvenient.
Support hidden in the left menu, you can quickly select the list in the connection list to view the corresponding relevant data
=> feat(desktop): add connection select when left list hide

src/views/connections/ConnectionsDetail.vue
When clicking the send button too quickly, received messages get replaced by sent messages, leading to message loss
#1614 #1770
Throttle the send message button to avoid rendering errors in the message list that may be caused by sending messages quickly in a short period.
=> feat(connections): add throttle to the send message button

src/components/MessageList.vue, src/utils/constant.ts, src/utils/messageQueue.ts, src/views/connections/ConnectionsDetail.vue
Currently, there are several issues with message handling in MQTTX:
1. Messages are lost when sending at high rates
2. Message rendering becomes out of order at high frequencies
3. Unable to load new messages when scrolling up/down
4. UI performance degrades significantly with high message rates
5. No optimization for different message rates scenarios
Issue Number: #1614 #1770
This PR introduces several improvements to message handling and rendering:
1. **Message Integrity**
- Fixed message loss during high-frequency publishing
- Ensured correct message sequencing
- Implemented reliable message storage and retrieval
2. **Scroll and Load Optimization**
- …
=> fix(desktop): fix loss messages issue

apps/desktop/src/renderer/components.d.ts, apps/desktop/src/renderer/src/components/update/Available.vue, apps/desktop/src/renderer/src/components/update/NotAvailable.vue, apps/desktop/src/renderer/src/components/update/View.vue, apps/web/components.d.ts, packages/tailwind-config/base.config.ts, packages/ui/components.d.ts, packages/ui/src/components/HelpView.vue, packages/ui/src/components/SettingsView.vue, packages/ui/src/components/about/View.vue, packages/ui/src/i18n/common.ts, packages/ui/src/i18n/update.ts
=> feat(ui): add ElScrollbar component for improved scrolling

apps/desktop/src/database/services/SettingsService.ts, apps/desktop/src/renderer/src/App.vue, apps/desktop/src/renderer/src/components/update/View.vue, apps/desktop/src/renderer/src/composables/useLog4.ts, apps/desktop/src/renderer/src/main.ts, apps/web/src/composables/useLog4.ts, apps/web/src/database/services/SettingsService.ts, apps/web/src/main.ts
The Settings Store is incorrectly configured, causing it to lose reactivity.
The Settings Store is now correctly configured, with optimized Watchers to prevent duplicated monitoring.
=> fix(settings): fix the incorrect use of the settings store

package.json
At present, the engine setting >= 16, but v18 cannot run, so we need to fix the node version to v16.
Example: #1833
```bash
❯ yarn
yarn install v1.22.22
[1/6] 🔍  Validating package.json...
error MQTTX@1.11.1: The engine "node" is incompatible with this module. Expected version "16". Got "18.17.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
=> chore(pkg): update node engine versiont to 16

apps/desktop/electron.vite.config.ts, apps/desktop/src/renderer/src/components/update/NotAvailable.vue, apps/desktop/src/renderer/src/env.d.ts, apps/web/env.d.ts, apps/web/vite.config.ts, packages/ui/auto-imports.d.ts, packages/ui/src/components/about/View.vue, packages/ui/src/composables/__test__/useLinks.test.ts, packages/ui/src/composables/useLinks.ts, packages/ui/src/vite-env.d.ts
Environment variables become invalid after packaging.
Environment variables remain intact after packaging.
=> fix(env): fix the issue of environment variable failure

eslint.config.mjs, examples/function/dynamicSwitch.js, examples/function/tempAndHum.js, examples/function/timestamp.js, packages/ui/src/components/script/function/Editor.vue, packages/ui/src/components/script/function/Test.vue, packages/ui/src/components/script/schema/Test.vue
Update custom function examples
=> refactor(examples): update custom function examples

apps/desktop/package.json, apps/desktop/src/database/services/SettingsService.ts, apps/desktop/src/main/config/contextMenu.ts, apps/desktop/src/main/config/contextMenuLabels.ts, apps/desktop/src/main/config/index.ts, apps/desktop/src/main/index.ts, apps/desktop/src/main/store.ts, apps/desktop/src/preload/index.d.ts, apps/desktop/src/preload/index.ts, pnpm-lock.yaml
There is no built-in context menu in Electron.
- Supports common context menu features, such as spell check, text options like Cut / Copy / Paste, and link options like Copy Link. Additionally, in development mode, an Inspect Element menu item is added for quickly viewing items in the inspector, similar to Chrome.
- Supports i18n for the context menu.
- Added store communication events to facilitate sharing simple data between the main process and renderer process.
=> feat(desktop): add electron-context-menu

packages/ui/src/components/MonacoEditor.vue, packages/ui/src/components/script/function/Editor.vue, packages/ui/src/components/script/schema/Editor.vue
Support customizing shortcut keys for the editor.
=> feat(editor): add customizable actions to Monaco editor components

apps/desktop/src/database/services/SettingsService.ts, apps/desktop/src/main/config/contextMenu.ts, apps/desktop/src/main/config/index.ts, apps/desktop/src/main/config/menu.ts, apps/desktop/src/main/config/nativeTheme.ts, apps/desktop/src/main/index.ts, apps/desktop/src/main/store.ts, apps/desktop/src/main/update.ts, packages/ui/src/components/SettingsView.vue, packages/ui/src/stores/useSettingsStore.ts
- Theme changes are only applied at the rendering layer, and there is no theme setting for Chromium, causing the window color not to change with the theme.
- The window background color is set only on startup and does not change with the theme.
\#1544
- The Chromium theme correctly follows the theme settings of the configuration page.
- The window background color can change with the theme.
=> feat(desktop): add native theme support and integrate with settings

src/components/ai/CopilotInput.vue
The dropdown menu reopens automatically after selecting custom generation options for the copilot feature. This creates a disruptive user experience as users must repeatedly dismiss the dropdown.
Fixed the dropdown behavior to stay closed after selecting a custom generation option. The dropdown will now only open when explicitly triggered by the user, creating a smoother interaction flow.
Testing should focus on verifying that the dropdown menu behaves correctly in all scenarios - it should open when clicked, but not reopen automatically after a selection is made.
This fix improves the overall UX of the preset prompt feature by making the input focus …
=> feat(copilot): improve preset prompt display behavior on input focus

src/utils/ai/copilot.ts, src/utils/ai/prompts/avroSchemaGen.txt, src/utils/ai/prompts/base.txt, src/utils/ai/prompts/protobufSchemaGen.txt
When requesting encoding/decoding help for message formats like Protobuf and Avro, the system sometimes returns both formats together inconsistently. The output formatting is also inconsistent across different AI models, with some responses lacking proper Markdown code blocks and structure.
- Separated Protobuf and Avro encoding/decoding into distinct system prompts
- Improved prompt instructions to enforce consistent Markdown formatting with proper code blocks
- Added constraints to ensure AI responses maintain consistent structure and format
- Optimized custom function return formats with explicit instructions for code block usage
Please test with various …
=> feat(copilot): support separate Protobuf and Avro schema generation prompts

package.json, src/background.ts, src/components/ImportData.vue, src/components/ImportScript.vue, src/main/newWindow.ts, src/main/updateDownloader.ts, src/store/modules/app.ts, src/utils/logger.ts, src/views/Home.vue, src/views/connections/ConnectionForm.vue, src/views/connections/ConnectionsDetail.vue, src/views/settings/index.vue, yarn.lock
If you have any questions, you can refer to the [Contributing Guide](https://github.com/emqx/MQTTX/blob/main/.github/CONTRIBUTING.md).
The current behavior involves using an older version of Electron in the project.
No specific issue is linked.
The new behavior involves updating Electron to version 22.0.0.
There are no specific instructions or things that need to be known prior to review.
This PR includes 395 additions and 559 deletions across 13 files, and it has 2 commits.
=> chore(pkg): bump electron version to 22.0.0

package.json, src/background.ts, src/components/ai/Copilot.vue, src/database/useConnection.ts, src/main/ai/mcp/MCPManager.ts, yarn.lock
When closing the application, an unhandled promise rejection occurs with error: `SQLITE_MISUSE: Database handle is closed`. This happens because the application attempts to close the database connection multiple times during the shutdown process, causing errors when trying to close an already closed connection.
Added safeguards to prevent multiple database connection close attempts:
1. Added a flag to track if connections have already been destroyed
2. Enhanced the connection destroy function with proper error handling
3. Modified app shutdown flow to avoid duplicate cleanup calls
4. Improved error handling in database connection management
This prevents …
=> fix(desktop): fix sqlite disconnect warning issue

cli/package.json, package.json, src/components/ai/Copilot.vue, src/components/ai/CopilotHeader.vue, src/components/ai/CopilotMessages.vue, src/components/ai/CopilotThinking.vue, src/database/database.config.ts, src/database/migration/1742835643809-reasonModelSupport.ts, src/database/models/CopilotEntity.ts, src/lang/copilot.ts, src/types/copilot.ts, src/utils/ai/AIAgent.ts, src/utils/ai/copilot.ts, src/utils/ai/prompts/base.txt, src/version.ts, src/views/connections/ConnectionsDetail.vue, web/package.json, yarn.lock
DeepSeek R1 and Claude 3.7 thought process not shown
=> feat(copilot): enhance reasoning support

apps/web/auto-imports.d.ts, examples/function/binaryData.js, examples/function/dynamicSwitch.js, examples/function/tempAndHum.js, examples/function/timestamp.js, packages/core/src/utils/payloadCodec.ts, packages/core/src/utils/payloadConverter.ts, packages/core/src/utils/sandbox.ts, packages/types/base.ts, packages/ui/src/components/script/function/Editor.vue, packages/ui/src/components/script/function/Test.vue, packages/ui/src/components/script/schema/Test.vue, packages/ui/src/composables/usePayloadConverter.ts, packages/ui/src/i18n/script.ts
- CBOR and MsgPack are currently treated as message display formats like Plaintext and Base64, but they should be considered as encoding/decoding methods.  
- Custom scripts currently cannot retrieve or modify raw data.  
- In script testing, it is not possible to select the message type
- Moved CBOR and MsgPack to the decoder category.  
- Introduced a `payloadRaw` parameter that allows users to retrieve and modify raw data as needed.  
- Added options in script testing to select the message type and configure the number of messages to send.  
- Improved data handling for custom script return values.  
Are there any specific instructions or things that …
=> improve(payload): move CBOR and MsgPack to the codec

src/components/ConnectionSelect.vue
The connection select at the top is not clickable; it only triggers window drag.
The issue is fixed — the select is now clickable as expected.
=> fix(desktop): prevent drag on connection list

.github/workflows/build_cli.yaml, .github/workflows/build_packages.yaml, .github/workflows/deploy_web.yaml
Currently, the CI/CD workflows for building packages, the CLI, and the web application trigger deployment/publishing actions (like uploading to AWS S3, publishing Docker images) for all GitHub releases, including pre-releases.
N/A
The GitHub Actions workflows (`build_packages.yaml`, `build_cli.yaml`, `deploy_web.yaml`) have been updated. Now, steps related to deploying to external services (AWS S3, Docker Hub) will only run for full releases (`release` event where `prerelease` is false). Actions like publishing to npm and deploying the website were already correctly configured. Uploading artifacts directly to the GitHub Release page remains unchanged and …
=> fix(ci): skip Docker/artifact uploads for pre-releases

package.json, src/types/copilot.ts, src/utils/ai/AIAgent.ts, src/utils/ai/copilot.ts, tests/unit/utils/ai/copilot.spec.ts, yarn.lock
Currently, MQTTX Copilot does not support using AI models from Google Generative AI (Gemini family). Users cannot select Google as a provider or utilize Gemini models for Copilot features.
None
This PR introduces support for Google Generative AI models within MQTTX Copilot. Users can now select 'Google' as a provider in the Copilot settings and choose from various Gemini models (e.g., `gemini-1.5-pro-latest`, `gemini-2.0-flash`, etc.).
Key changes include:
*   Added the `@ai-sdk/google` dependency.
*   Updated type definitions (`src/types/copilot.ts`) to include the Google provider configuration (`GoogleOptionsModel`).
*   Updated `AImodelsOptions` in …
=> feat(copilot): google gemini support

package.json, scripts/patch-azure-sdk.js, src/types/copilot.ts, src/utils/ai/AIAgent.ts, src/utils/ai/copilot.ts, yarn.lock
The application currently does not support Azure OpenAI as an AI provider option. Users cannot configure or utilize Azure OpenAI models for AI features like Copilot.
None
This PR introduces support for Azure OpenAI as an AI provider. Users can now select 'Azure OpenAI' in the AI settings and configure their Azure endpoint (either via Resource Name or full URL) and API key. This enables the use of various Azure OpenAI models (e.g., `deployment-gpt-4o`, `deployment-gpt-4.1-mini`, etc.) within the application's AI features.
Key changes include:
*   Added 'Azure OpenAI' to `AImodelsOptions` in `src/utils/ai/copilot.ts`.
*   The corresponding Azure OpenAI models …
=> feat(copilot): add Azure OpenAI support

src/background.ts
> For any questions, see our [Contributing Guide](https://github.com/emqx/MQTTX/blob/main/.github/CONTRIBUTING.md)
DevTools are disabled by default in both development and production builds.  
When a white screen or rendering error occurs, contributors cannot open the console, inspect network traffic, or profile performance, making root-cause analysis slow and screenshot-dependent.
Fixes：
- Production builds keep the shortcut **Ctrl + Shift + I / Cmd + Opt + I** to allow on-site debugging.
- DevTools load only when explicitly enabled, so default performance and bundle size remain unchanged.
- A future improvement could capture `console.error` messages and upload them automatically, reducing manual log collection.
=> refactor(background): enable devTools in BrowserWindow configuration

src/components/MsgLeftItem.vue, src/components/MsgRightItem.vue, src/utils/highlightSearch.ts
Broken display for messages consisting of tags
Fixes #1963 
Fixes the render of messages, XML tags and special characters now highlight correctly when searched. The `highlightSearchTerm` function now searches in original text.
=> fix(MsgItem): correct highlight logic to handle payload when no search params

.gitignore, babel.config.js, src/utils/xmlUtils.ts, src/widgets/TreeNodeInfo.vue, src/widgets/TreeView.vue, tests/unit/utils/xmlUtils.spec.ts
If you have any questions, you can refer to the
[Contributing Guide](https://github.com/emqx/MQTTX/blob/main/.github/CONTRIBUTING.md)
In the Topics Tree view, when connection names with
long hostnames are displayed (e.g., `FlowMQ@fmq0c7b67ec
fcef4ecd.tiger.dev.us-east-1.flowmq.link`), the text
overflows and pushes the message count (`3 msgs`) and
sub-topics count out of view, making them unreadable.
Additionally, long URLs in the right panel
(TreeNodeInfo) don't wrap properly and overflow their
container.
N/A
- Long connection names in the topic tree now display
with text truncation and ellipsis when they exceed
available space
- A tooltip appears on hover (after 500ms delay)
showing the full `connectionName@host` when text length
exceeds 50 characters
- The message count and sub-topics …
=> fix(TopicTree): improve long host name display with ellipsis and tooltip

src/background.ts, src/database/database.config.ts, src/main/appDataPath.ts, src/main/installCLI.ts
**Problem**
MQTTX on Windows had issues with application data storage due to %APPDATA% directory redirection. The `appdata-path` library doesn't handle Windows %APPDATA% redirection properly, causing:
1. Data location inconsistency
2. Data loss during Windows updates
3. Permission issues
**Root Cause**
Application relied on `appdata-path` npm package instead of Electron's native `app.getPath('userData')` API.
**Solution**
- Created unified app data path system using Electron's native API (`src/main/appDataPath.ts`)
- Added automatic data migration from legacy paths
- Updated database configuration and CLI installer
- Added migration logic in background …
=> fix(desktop): unify app data path handling to fix Windows %APPDATA% redirect issue

src/components/KeyValueEditor.vue
**What is the current behavior?**
When navigating in the Topics Tree from one leaf with User Properties to another one with User Properties they don't get updated. (in the topic-info-card)
**What is the new behavior?**
Now when switching from one leaf to another the User Properties get updated as disabled is set to true in this view.
**Does this PR introduce a breaking change?**
=> fix(KeyValueEditor.vue): fix a User Property display bug in Topics Tree
